import { ClinicalProtocol } from '../types';
import { ProtocolRegistry } from './ProtocolRegistry';

const healthyProtocols: ClinicalProtocol[] = [
  {
    id: 'healthy_adult',
    category: 'healthy_adult',
    phase: 'healthy',
    name: 'Healthy Adult Nutrition',
    nameAr: 'تغذية بالغ سليم',
    nutrientTargets: {
      calories: '25-30 kcal/kg',
      protein: 0.8,
      carbsPercent: 55,
      fatPercent: 30,
      fluid: '30 ml/kg',
    },
    guidelines: ['WHO Healthy Diet Guidelines', 'ESPEN General Nutrition'],
    specialConsiderations: [
      'توازن المغذيات الكبرى (كربوهيدرات 55%، بروتين 15%، دهون 30%)',
      'تناول ألياف غذائية 25-30 غم/يوم',
      'تقليل السكريات المضافة والدهون المشبعة',
      'شرب كمية كافية من الماء (8 أكواب/يوم)',
    ],
    contraindications: [],
    monitoringRequirements: ['الوزن شهرياً', 'مؤشر كتلة الجسم', 'محيط الخصر'],
  },
  {
    id: 'healthy_elderly',
    category: 'healthy_elderly',
    phase: 'healthy',
    name: 'Elderly Nutrition',
    nameAr: 'تغذية كبار السن',
    nutrientTargets: {
      calories: '25-30 kcal/kg',
      protein: 1.2,
      carbsPercent: 50,
      fatPercent: 35,
      fluid: '30 ml/kg',
      specialNutrients: ['كالسيوم 1200 ملغ/يوم', 'فيتامين د 800 وحدة/يوم', 'فيتامين ب12'],
    },
    guidelines: ['ESPEN Elderly Guidelines', 'WHO Aging Guidelines'],
    specialConsiderations: [
      'زيادة البروتين (1.2 غ/كلغ) للوقاية من هزال العضلات (Sarcopenia)',
      'فيتامين د والكالسيوم لصحة العظام',
      'فيتامين ب12 (امتصاصه يقل مع العمر)',
      'تقسيم الوجبات إلى 5-6 وجبات صغيرة',
    ],
    contraindications: [],
    monitoringRequirements: ['الوزن شهرياً', 'كتلة العضلات', 'كثافة العظام سنوياً'],
  },
];

const pediatricProtocols: ClinicalProtocol[] = [
  {
    id: 'infant',
    category: 'infant',
    phase: 'pediatrics',
    name: 'Infant Nutrition (0-12 months)',
    nameAr: 'تغذية رضيع (0-12 شهر)',
    nutrientTargets: {
      calories: '100-120 kcal/kg',
      protein: 1.5,
      carbsPercent: 40,
      fatPercent: 45,
      fluid: '100-150 ml/kg',
      specialNutrients: ['حديد 11 ملغ/يوم', 'فيتامين د 400 وحدة/يوم'],
    },
    guidelines: ['AAP Infant Guidelines', 'ESPEN Pediatric Nutrition'],
    specialConsiderations: [
      'الرضاعة الطبيعية حصراً لأول 6 أشهر',
      'بدء إدخال الطعام الصلب من عمر 6 أشهر',
      'تجنب العسل في السنة الأولى',
      'مكمل فيتامين د 400 وحدة/يوم من الولادة',
    ],
    contraindications: ['حليب البقر قبل 12 شهر', 'العسل', 'الأطعمة الصلبة قبل 4 أشهر'],
    monitoringRequirements: ['مخطط النمو (وزن/طول/محيط رأس) شهرياً', 'تقييم التطور الغذائي'],
  },
  {
    id: 'toddler',
    category: 'toddler',
    phase: 'pediatrics',
    name: 'Toddler Nutrition (1-3 years)',
    nameAr: 'تغذية طفل صغير (1-3 سنوات)',
    nutrientTargets: {
      calories: '1000-1400 kcal/day',
      protein: 1.0,
      carbsPercent: 50,
      fatPercent: 30,
      fluid: '1000-1500 ml/day',
    },
    guidelines: ['AAP Toddler Guidelines'],
    specialConsiderations: [
      'وجبات صغيرة متكررة (5-6 وجبات/يوم)',
      'تقديم أصناف متنوعة من الخضار والفواكه',
      'تجنب السكريات المضافة والمشروبات الغازية',
      'تشجيع الأكل الذاتي',
    ],
    contraindications: ['السكريات المضافة', 'المشروبات الغازية', 'الأطعمة صغيرة الحجم (خطر الاختناق)'],
    monitoringRequirements: ['مخطط النمو شهرياً', 'تقييم سلوك الأكل'],
  },
  {
    id: 'child',
    category: 'child',
    phase: 'pediatrics',
    name: 'Child Nutrition (4-12 years)',
    nameAr: 'تغذية طفل (4-12 سنة)',
    nutrientTargets: {
      calories: '1400-2200 kcal/day',
      protein: 0.9,
      carbsPercent: 55,
      fatPercent: 30,
      fluid: '1500-2000 ml/day',
    },
    guidelines: ['AAP Child Guidelines', 'ESPEN Pediatric Nutrition'],
    specialConsiderations: [
      'تشجيع النشاط البدني اليومي (60 دقيقة على الأقل)',
      'الحد من وقت الشاشات (أقل من ساعتين/يوم)',
      'وجبة إفطار متوازنة يومياً',
      'تقليل الأطعمة المصنعة والوجبات السريعة',
    ],
    contraindications: [],
    monitoringRequirements: ['مخطط النمو شهرياً', 'مؤشر كتلة الجسم سنوياً'],
  },
  {
    id: 'adolescent',
    category: 'adolescent',
    phase: 'pediatrics',
    name: 'Adolescent Nutrition (13-18 years)',
    nameAr: 'تغذية مراهق (13-18 سنة)',
    nutrientTargets: {
      calories: '2000-3200 kcal/day',
      protein: 0.85,
      carbsPercent: 55,
      fatPercent: 30,
      fluid: '2000-3000 ml/day',
      specialNutrients: ['كالسيوم 1300 ملغ/يوم', 'حديد 11 ملغ/يوم للإناث'],
    },
    guidelines: ['AAP Adolescent Guidelines'],
    specialConsiderations: [
      'زيادة احتياجات الحديد للإناث بعد البلوغ',
      'دعم صحة العظام بالكالسيوم وفيتامين د',
      'تجنب المشروبات الغازية والطاقة',
      'تشجيع النشاط البدني المنتظم',
    ],
    contraindications: [],
    monitoringRequirements: ['مخطط النمو شهرياً', 'فحص الهيموغلوبين سنوياً'],
  },
];

const pregnancyProtocols: ClinicalProtocol[] = [
  {
    id: 'pregnancy_normal',
    category: 'pregnancy_normal',
    phase: 'pregnancy',
    name: 'Normal Pregnancy Nutrition',
    nameAr: 'تغذية حمل طبيعي',
    nutrientTargets: {
      calories: '+300 kcal/day (2nd and 3rd trimester)',
      protein: 1.1,
      carbsPercent: 50,
      fatPercent: 30,
      fluid: '3000 ml/day',
      specialNutrients: ['حديد 27 ملغ/يوم', 'حمض فوليك 600 ميكروغرام/يوم', 'كالسيوم 1000 ملغ/يوم'],
    },
    guidelines: ['ACOG Pregnancy Guidelines', 'WHO Antenatal Care Guidelines'],
    specialConsiderations: [
      'مكمل حمض الفوليك 400-600 ميكروغرام/يوم قبل الحمل وأول 12 أسبوع',
      'مكمل حديد 27 ملغ/يوم من الأسبوع 12',
      'تجنب الكحول والتدخين تماماً',
      'الحد من الكافيين (أقل من 200 ملغ/يوم)',
      'تجنب الأجبان غير المبسترة واللحوم النيئة',
    ],
    contraindications: ['الكحول', 'التدخين', 'الكافيين الزائد', 'الأجبان غير المبسترة'],
    monitoringRequirements: [
      'الوزن شهرياً',
      'فحص سكر الحمل (24-28 أسبوع)',
      'ضغط الدم كل زيارة',
      'مستوى الحديد وفيتامين د',
    ],
  },
  {
    id: 'pregnancy_high_risk',
    category: 'pregnancy_high_risk',
    phase: 'pregnancy',
    name: 'High-Risk Pregnancy Nutrition',
    nameAr: 'تغذية حمل عالي الخطورة',
    nutrientTargets: {
      calories: '+350 kcal/day',
      protein: 1.3,
      carbsPercent: 40,
      fatPercent: 35,
      fluid: '2500 ml/day',
      glucoseTarget: '<140 mg/dL',
      specialNutrients: ['حديد 27 ملغ/يوم', 'حمض فوليك 1000 ميكروغرام/يوم'],
    },
    guidelines: ['ACOG High-Risk Pregnancy Guidelines'],
    specialConsiderations: [
      'مراقبة سكر الدم 4 مرات/يوم',
      'تقليل الصوديوم (أقل من 2000 ملغ/يوم)',
      'مكملات إضافية حسب الحالة (كالسيوم، مغنيسيوم)',
      'مراقبة ضغط الدم يومياً',
    ],
    contraindications: ['الكحول', 'التدخين', 'الصوديوم الزائد'],
    monitoringRequirements: [
      'وزن كل أسبوعين',
      'سكر الدم 4 مرات/يوم',
      'ضغط الدم يومياً',
      'فحص البول للبروتين',
    ],
  },
  {
    id: 'lactation',
    category: 'lactation',
    phase: 'pregnancy',
    name: 'Lactation Nutrition',
    nameAr: 'تغذية رضاعة',
    nutrientTargets: {
      calories: '+500 kcal/day',
      protein: 1.3,
      carbsPercent: 50,
      fatPercent: 30,
      fluid: '3500 ml/day',
      specialNutrients: ['حديد 9 ملغ/يوم', 'كالسيوم 1000 ملغ/يوم'],
    },
    guidelines: ['ACOG Lactation Guidelines', 'WHO Breastfeeding Guidelines'],
    specialConsiderations: [
      'زيادة السوائل (3.5 لتر/يوم) لإدرار الحليب',
      'تجنب الأدوية الممنوعة في الرضاعة',
      'تقليل الكافيين (أقل من 300 ملغ/يوم)',
      'تناول أطعمة غنية بالكالسيوم والحديد',
    ],
    contraindications: ['الكحول', 'التدخين', 'الأدوية الممنوعة في الرضاعة'],
    monitoringRequirements: ['وزن الأم شهرياً', 'مخطط نمو الرضيع', 'تقييم إدرار الحليب'],
  },
];

const sportsProtocols: ClinicalProtocol[] = [
  {
    id: 'endurance_athlete',
    category: 'endurance_athlete',
    phase: 'sports',
    name: 'Endurance Athlete Nutrition',
    nameAr: 'تغذية رياضي تحمل',
    nutrientTargets: {
      calories: '35-40 kcal/kg',
      protein: 1.2,
      carbsPercent: 70,
      fatPercent: 20,
      fluid: '500-1000 ml/hour during exercise',
      specialNutrients: ['صوديوم 500-700 ملغ/لتر ماء أثناء التمرين'],
    },
    guidelines: ['ISSN Endurance Guidelines', 'ACSM Sports Nutrition'],
    specialConsiderations: [
      'تحميل الكربوهيدرات قبل المنافسة (10-12 غ/كلغ/يوم)',
      'تعويض السوائل والكهارل أثناء التمرين',
      'تناول 20-30 غم بروتين بعد التمرين (within 30 min)',
      'وجبة خفيفة قبل التمرين (1-4 ساعات) تحتوي كربوهيدرات',
    ],
    contraindications: [],
    monitoringRequirements: ['الوزن قبل وبعد التمرين', 'فحص الجفاف', 'تقييم الأداء الرياضي'],
  },
  {
    id: 'strength_athlete',
    category: 'strength_athlete',
    phase: 'sports',
    name: 'Strength Athlete Nutrition',
    nameAr: 'تغذية رياضي قوة',
    nutrientTargets: {
      calories: '35-40 kcal/kg',
      protein: 1.8,
      carbsPercent: 50,
      fatPercent: 25,
      fluid: '500-1000 ml/hour',
      specialNutrients: ['كرياتين 3-5 غم/يوم'],
    },
    guidelines: ['ISSN Strength Guidelines', 'ACSM Sports Nutrition'],
    specialConsiderations: [
      'توزيع البروتين على 4-6 وجبات (20-40 غم بروتين/وجبة)',
      'تناول بروتين بعد التمرين مباشرة (30-40 غم)',
      'الكرياتين مكمل فعال (3-5 غم/يوم)',
      'الكربوهيدرات لدعم الأداء والتعافي',
    ],
    contraindications: ['مكملات غير مدروسة'],
    monitoringRequirements: ['كتلة العضلات شهرياً', 'نسبة الدهون شهرياً', 'تقييم القوة'],
  },
  {
    id: 'recreational_athlete',
    category: 'recreational_athlete',
    phase: 'sports',
    name: 'Recreational Athlete Nutrition',
    nameAr: 'تغذية رياضي هواة',
    nutrientTargets: {
      calories: '30-35 kcal/kg',
      protein: 1.0,
      carbsPercent: 55,
      fatPercent: 30,
      fluid: '30 ml/kg',
    },
    guidelines: ['ISSN Recreational Guidelines'],
    specialConsiderations: [
      'تغذية متوازنة مع تنويع المصادر الغذائية',
      'ترطيب كافٍ قبل وأثناء وبعد التمرين',
      'وجبة خفيفة بعد التمرين (بروتين + كربوهيدرات)',
    ],
    contraindications: [],
    monitoringRequirements: ['الوزن', 'تقييم الأداء', 'مستوى الطاقة'],
  },
];

const weightProtocols: ClinicalProtocol[] = [
  {
    id: 'obesity_loss',
    category: 'obesity_loss',
    phase: 'weight_management',
    name: 'Obesity Weight Loss',
    nameAr: 'فقدان الوزن للسمنة',
    nutrientTargets: {
      calories: 'TEE - 500 kcal/day',
      protein: 1.3,
      carbsPercent: 40,
      fatPercent: 35,
      fluid: '30 ml/kg',
      specialNutrients: ['ألياف 30-40 غم/يوم'],
    },
    guidelines: ['AMA Obesity Guidelines', 'AHA/ACC/TOS Guidelines'],
    specialConsiderations: [
      'عجز سعري 500-750 ك.ك/يوم لخسارة 0.5-1 كغم/أسبوع',
      'بروتين مرتفع (1.3 غ/كلغ) للحفاظ على الكتلة العضلية',
      'ألياف عالية (30-40 غم) للشعور بالشبع',
      'نشاط بدني 150-300 دقيقة/أسبوع',
    ],
    contraindications: ['الحميات القاسية (أقل من 800 ك.ك/يوم)', 'الصيام المتقطع لبعض الحالات'],
    monitoringRequirements: [
      'وزن أسبوعي',
      'محيط الخصر شهرياً',
      'دهون الدم كل 3 أشهر',
      'ضغط الدم شهرياً',
    ],
  },
  {
    id: 'underweight_gain',
    category: 'underweight_gain',
    phase: 'weight_management',
    name: 'Underweight Weight Gain',
    nameAr: 'زيادة الوزن للنحافة',
    nutrientTargets: {
      calories: 'TEE + 500 kcal/day',
      protein: 1.5,
      carbsPercent: 55,
      fatPercent: 30,
      fluid: '30 ml/kg',
    },
    guidelines: ['ASPEN Weight Gain Guidelines'],
    specialConsiderations: [
      'فائض سعري 300-500 ك.ك/يوم',
      'وجبات صغيرة متكررة 5-6/يوم',
      'مكملات غذائية عالية السعرات والبروتين',
      'تمارين مقاومة لبناء الكتلة العضلية',
    ],
    contraindications: [],
    monitoringRequirements: ['وزن أسبوعي', 'كتلة العضلات شهرياً'],
  },
];

const chronicProtocols: ClinicalProtocol[] = [
  {
    id: 'diabetes_t1',
    category: 'diabetes_t1',
    phase: 'chronic_disease',
    name: 'Type 1 Diabetes Nutrition',
    nameAr: 'تغذية سكري نوع 1',
    nutrientTargets: {
      calories: 'TEE',
      protein: 1.0,
      carbsPercent: 45,
      fatPercent: 35,
      fluid: '30 ml/kg',
      glucoseTarget: '80-140 mg/dL',
    },
    guidelines: ['ADA Diabetes Guidelines', 'ISPAD Guidelines'],
    specialConsiderations: [
      'حساب الكربوهيدرات (Carbohydrate Counting)',
      'جرعات الأنسولين تتناسب مع كمية الكربوهيدرات',
      'توزيع الوجبات (3 رئيسية + 2-3 خفيفة)',
      'مراقبة سكر الدم 4-6 مرات/يوم',
    ],
    contraindications: ['السكريات السائلة المركزة'],
    monitoringRequirements: [
      'سكر الدم 4-6 مرات/يوم',
      'HbA1c كل 3 أشهر',
      'وظائف الكلى سنوياً',
    ],
  },
  {
    id: 'diabetes_t2',
    category: 'diabetes_t2',
    phase: 'chronic_disease',
    name: 'Type 2 Diabetes Nutrition',
    nameAr: 'تغذية سكري نوع 2',
    nutrientTargets: {
      calories: 'TEE (or TEE-500 if overweight)',
      protein: 1.2,
      carbsPercent: 35,
      fatPercent: 45,
      fluid: '30 ml/kg',
      glucoseTarget: '80-140 mg/dL',
      specialNutrients: ['ألياف 25-30 غم/يوم'],
    },
    guidelines: ['ADA Diabetes Guidelines', 'EASD Guidelines'],
    specialConsiderations: [
      'خفض الكربوهيدرات إلى 35% من إجمالي السعرات',
      'دهون صحية غير مشبعة (45%) - زيت زيتون، أفوكادو، مكسرات',
      'فقدان الوزن 5-10% من الوزن الحالي',
      'النشاط البدني 150 دقيقة/أسبوع على الأقل',
    ],
    contraindications: ['الدهون المتحولة', 'السكريات المضافة', 'الكربوهيدرات المكررة'],
    monitoringRequirements: [
      'سكر الدم 2-4 مرات/يوم',
      'HbA1c كل 3 أشهر',
      'دهون الدم سنوياً',
    ],
  },
  {
    id: 'ckd_nondialysis',
    category: 'ckd_nondialysis',
    phase: 'chronic_disease',
    name: 'CKD Non-Dialysis Nutrition',
    nameAr: 'تغذية كلى غير دياليزا',
    nutrientTargets: {
      calories: '30-35 kcal/kg',
      protein: 0.7,
      carbsPercent: 55,
      fatPercent: 30,
      fluid: '30 ml/kg',
      specialNutrients: ['بوتاسيوم أقل من 2000 ملغ/يوم', 'فوسفور أقل من 800 ملغ/يوم', 'صوديوم أقل من 2000 ملغ/يوم'],
    },
    guidelines: ['KDIGO CKD Guidelines', 'NKF KDOQI Guidelines'],
    specialConsiderations: [
      'تقييد البروتين 0.6-0.8 غ/كلغ لإبطاء تقدم المرض',
      'تقييد البوتاسيوم حسب مستواه في الدم',
      'تقييد الفوسفور وتجنب الأغذية عالية الفوسفور',
      'تجنب الأغذية عالية الصوديوم',
    ],
    contraindications: [
      'الأغذية عالية البوتاسيوم (موز، طماطم، برتقال، مشمش، بطاطا)',
      'الأغذية عالية الفوسفور (أجبان، مكسرات، مشروبات غازية)',
    ],
    monitoringRequirements: [
      'وظائف الكلى شهرياً',
      'بوتاسيوم أسبوعياً',
      'فوسفور شهرياً',
      'ألبومين شهرياً',
    ],
  },
  {
    id: 'ckd_dialysis',
    category: 'ckd_dialysis',
    phase: 'chronic_disease',
    name: 'CKD Dialysis Nutrition',
    nameAr: 'تغذية كلى دياليزا',
    nutrientTargets: {
      calories: '35 kcal/kg',
      protein: 1.2,
      carbsPercent: 55,
      fatPercent: 30,
      fluid: '2000-2500 ml/day',
      specialNutrients: ['بروتين مرتفع 1.2 غ/كلغ', 'بوتاسيوم أقل من 3000 ملغ/يوم'],
    },
    guidelines: ['KDIGO Dialysis Guidelines', 'NKF KDOQI Dialysis'],
    specialConsiderations: [
      'بروتين 1.2 غ/كلغ لتعويض الفقد خلال الغسيل الكلوي',
      'تقييد السوائل حسب إخراج البول',
      'تقييد الفوسفور (800-1000 ملغ/يوم)',
      'تناول مكملات الفيتامينات المائية (بعد استشارة الطبيب)',
    ],
    contraindications: ['الأغذية عالية الفوسفور', 'السوائل الزائدة'],
    monitoringRequirements: [
      'وزن يومي',
      'وظائف الكلى أسبوعياً',
      'بوتاسيوم أسبوعياً',
      'فوسفور شهرياً',
      'ألبومين شهرياً',
    ],
  },
  {
    id: 'cardiovascular',
    category: 'cardiovascular',
    phase: 'chronic_disease',
    name: 'Cardiovascular Nutrition',
    nameAr: 'تغذية أمراض القلب',
    nutrientTargets: {
      calories: 'TEE or TEE - 500 (if overweight)',
      protein: 1.0,
      carbsPercent: 50,
      fatPercent: 30,
      fluid: '30 ml/kg',
      specialNutrients: ['أوميغا-3 1-2 غم/يوم', 'ألياف 25-30 غم/يوم'],
    },
    guidelines: ['AHA Cardiovascular Guidelines', 'ACC/AHA Guidelines'],
    specialConsiderations: [
      'حمية البحر المتوسط (Mediterranean Diet)',
      'تقليل الدهون المشبعة (أقل من 7% من السعرات)',
      'تقليل الصوديوم (أقل من 2000 ملغ/يوم)',
      'أوميغا-3 من الأسماك الدهنية مرتين/أسبوع',
    ],
    contraindications: ['الدهون المتحولة', 'الدهون المشبعة المرتفعة', 'الصوديوم المرتفع'],
    monitoringRequirements: [
      'دهون الدم كل 3-6 أشهر',
      'ضغط الدم شهرياً',
      'الوزن شهرياً',
    ],
  },
  {
    id: 'hypertension',
    category: 'hypertension',
    phase: 'chronic_disease',
    name: 'Hypertension Nutrition (DASH Diet)',
    nameAr: 'تغذية ارتفاع ضغط الدم (DASH)',
    nutrientTargets: {
      calories: 'TEE or TEE - 500 (if overweight)',
      protein: 1.0,
      carbsPercent: 55,
      fatPercent: 30,
      fluid: '30 ml/kg',
      specialNutrients: ['صوديوم أقل من 1500 ملغ/يوم', 'بوتاسيوم 4700 ملغ/يوم', 'كالسيوم 1250 ملغ/يوم'],
    },
    guidelines: ['AHA Hypertension Guidelines', 'DASH Diet Guidelines'],
    specialConsiderations: [
      'حمية DASH (خضار، فواكه، حبوب كاملة، ألبان قليلة الدسم)',
      'صوديوم أقل من 1500 ملغ/يوم (ideal)',
      'زيادة البوتاسيوم من المصادر الطبيعية',
      'تقليل الكحول والكافيين',
    ],
    contraindications: ['الأغذية المصنعة', 'الملح المضاف', 'الكحول'],
    monitoringRequirements: ['ضغط الدم أسبوعياً', 'وظائف الكلى سنوياً'],
  },
];

const criticalCareProtocols: ClinicalProtocol[] = [
  {
    id: 'icu_ventilated',
    category: 'icu_ventilated',
    phase: 'critical_care',
    name: 'ICU Ventilated Nutrition',
    nameAr: 'تغذية عناية مركزة - مريض متصل بجهاز تنفس',
    nutrientTargets: {
      calories: '25-30 kcal/kg',
      protein: 1.8,
      carbsPercent: 40,
      fatPercent: 45,
      fluid: '30 ml/kg',
      glucoseTarget: '80-150 mg/dL',
    },
    guidelines: ['ESPEN ICU Guidelines 2023', 'ASPEN Critical Care Guidelines', 'SSC Guidelines'],
    specialConsiderations: [
      'تغذية معوية مبكرة خلال 24-48 ساعة من الدخول',
      'بروتين عالي (1.5-2.0 غ/كلغ) لمنع هزال العضلات',
      'كربوهيدرات منخفضة (40%) لتقليل إنتاج CO2',
      'دهون مرتفعة (45%) كمصدر طاقة بديل',
    ],
    contraindications: ['فرط التغذية (لا تتجاوز TEE)', 'إعطاء تغذية وريدية إذا كانت المعوية ممكنة'],
    monitoringRequirements: [
      'سكر الدم كل 6 ساعات',
      'إلكتروليتات يومياً',
      'توازن السوائل يومياً',
      'فحص وظائف الكبد أسبوعياً',
    ],
  },
  {
    id: 'icu_non_ventilated',
    category: 'icu_non_ventilated',
    phase: 'critical_care',
    name: 'ICU Non-Ventilated Nutrition',
    nameAr: 'تغذية عناية مركزة - غير متصل بجهاز تنفس',
    nutrientTargets: {
      calories: '25-30 kcal/kg',
      protein: 1.5,
      carbsPercent: 45,
      fatPercent: 40,
      fluid: '30 ml/kg',
    },
    guidelines: ['ESPEN ICU Guidelines', 'ASPEN Critical Care'],
    specialConsiderations: [
      'تغذية معوية مبكرة',
      'بروتين معتدل-مرتفع (1.5 غ/كلغ)',
      'مراقبة علامات سوء التغذية',
    ],
    contraindications: [],
    monitoringRequirements: ['سكر الدم يومياً', 'إلكتروليتات يومياً', 'توازن السوائل'],
  },
  {
    id: 'sepsis',
    category: 'sepsis',
    phase: 'critical_care',
    name: 'Sepsis Nutrition',
    nameAr: 'تغذية تسمم الدم (Sepsis)',
    nutrientTargets: {
      calories: '25-30 kcal/kg',
      protein: 1.8,
      carbsPercent: 40,
      fatPercent: 45,
      fluid: '30 ml/kg',
      glucoseTarget: '80-150 mg/dL',
    },
    guidelines: ['SSC Sepsis Guidelines', 'ESPEN ICU Guidelines'],
    specialConsiderations: [
      'البدء المبكر بالتغذية المعوية (خلال 24 ساعة)',
      'بروتين عالي (1.5-2.0 غ/كلغ) لتعويض الهدم',
      'سيطرة صارمة على سكر الدم',
      'مراقبة علامات الالتهاب والاستجابة للعلاج',
    ],
    contraindications: ['فرط التغذية في المرحلة الحادة'],
    monitoringRequirements: [
      'سكر الدم كل 4-6 ساعات',
      'إلكتروليتات يومياً',
      'علامات الالتهاب (CRP, PCT)',
      'توازن السوائل كل 8 ساعات',
    ],
  },
  {
    id: 'trauma',
    category: 'trauma',
    phase: 'critical_care',
    name: 'Trauma Nutrition',
    nameAr: 'تغذية الصدمات والإصابات',
    nutrientTargets: {
      calories: '30-35 kcal/kg',
      protein: 2.0,
      carbsPercent: 50,
      fatPercent: 35,
      fluid: '30 ml/kg',
    },
    guidelines: ['ASPEN Trauma Guidelines', 'EAST Guidelines'],
    specialConsiderations: [
      'احتياجات طاقية مرتفعة (30-35 ك.ك/كلغ) بسبب فرط الأيض',
      'بروتين عالي جداً (2.0 غ/كلغ) لتعويض الهدم البروتيني',
      'تغذية معوية فورية إن أمكن',
      'مراقبة الحالة التغذوية عن كثب',
    ],
    contraindications: [],
    monitoringRequirements: [
      'توازن نيتروجين أسبوعياً',
      'إلكتروليتات يومياً',
      'علامات الالتهاب',
      'وظائف الأعضاء',
    ],
  },
];

const specialProtocols: ClinicalProtocol[] = [
  {
    id: 'gastrointestinal',
    category: 'gastrointestinal',
    phase: 'special_conditions',
    name: 'Gastrointestinal Disease Nutrition',
    nameAr: 'تغذية أمراض الجهاز الهضمي',
    nutrientTargets: {
      calories: '30-35 kcal/kg',
      protein: 1.3,
      carbsPercent: 50,
      fatPercent: 30,
      fluid: '30 ml/kg',
      specialNutrients: ['ألياف منخفضة في النوبة', 'ألياف عالية في مرحلة الهدوء'],
    },
    guidelines: ['ASPEN GI Guidelines', 'ECCO Guidelines (IBD)'],
    specialConsiderations: [
      'خلال النوبات: ألياف منخفضة، وجبات صغيرة متكررة',
      'خلال الهدوء: ألياف عالية، بروبيوتيك',
      'تجنب الأغذية المهيجة (حارة، دهون عالية)',
      'مكملات فيتامين د والحديد حسب نوع المرض',
    ],
    contraindications: ['الأغذية الحارة', 'الكافيين في النوبات', 'اللاكتوز في حالات عدم التحمل'],
    monitoringRequirements: ['الوزن أسبوعياً', 'فيتامين د شهرياً', 'حديد شهرياً'],
  },
  {
    id: 'liver_disease',
    category: 'liver_disease',
    phase: 'special_conditions',
    name: 'Liver Disease Nutrition',
    nameAr: 'تغذية أمراض الكبد',
    nutrientTargets: {
      calories: '35 kcal/kg',
      protein: 1.3,
      carbsPercent: 50,
      fatPercent: 30,
      fluid: '30 ml/kg',
      specialNutrients: ['صوديوم أقل من 2000 ملغ/يوم', 'فيتامين ك (حسب الحالة)'],
    },
    guidelines: ['AASLD Liver Guidelines', 'EASL Guidelines'],
    specialConsiderations: [
      'تجنب الكحول تماماً',
      'بروتين كافٍ (1.3 غ/كلغ) إلا في حالة الاعتلال الدماغي الكبدي',
      'صوديوم منخفض في حالة الوذمة أو الاستسقاء',
      'مكمل فيتامين ك وفيتامين د والكالسيوم',
    ],
    contraindications: ['الكحول', 'الحديد الزائد (في داء ترسب الأصبغة الدموية)'],
    monitoringRequirements: [
      'وظائف الكبد شهرياً',
      'ألبومين شهرياً',
      'INR شهرياً',
      'صوديوم أسبوعياً',
    ],
  },
  {
    id: 'respiratory_disease',
    category: 'respiratory_disease',
    phase: 'special_conditions',
    name: 'Respiratory Disease Nutrition',
    nameAr: 'تغذية أمراض الجهاز التنفسي',
    nutrientTargets: {
      calories: '30-35 kcal/kg',
      protein: 1.3,
      carbsPercent: 40,
      fatPercent: 45,
      fluid: '30 ml/kg',
    },
    guidelines: ['ASPEN Respiratory Guidelines', 'ERS Guidelines'],
    specialConsiderations: [
      'كربوهيدرات منخفضة (40%) لتقليل إنتاج CO2',
      'دهون مرتفعة (45%) كمصدر طاقة بديل لتقليل الحمل التنفسي',
      'وجبات صغيرة متكررة لتجنب عسر التنفس بعد الأكل',
      'فيتامين د والمغنيسيوم لصحة العضلات التنفسية',
    ],
    contraindications: ['الكربوهيدرات العالية', 'الوجبات الكبيرة'],
    monitoringRequirements: ['غازات الدم الشرياني', 'الوزن أسبوعياً', 'فيتامين د شهرياً'],
  },
  {
    id: 'oncology',
    category: 'oncology',
    phase: 'special_conditions',
    name: 'Oncology Nutrition',
    nameAr: 'تغذية مرضى الأورام',
    nutrientTargets: {
      calories: '35-40 kcal/kg',
      protein: 1.5,
      carbsPercent: 50,
      fatPercent: 30,
      fluid: '30 ml/kg',
      specialNutrients: ['أوميغا-3 2-3 غم/يوم'],
    },
    guidelines: ['ASPEN Oncology Guidelines', 'ESPEN Cancer Guidelines'],
    specialConsiderations: [
      'بروتين عالي (1.5 غ/كلغ) للوقاية من الدنف (Cachexia)',
      'أوميغا-3 لدعم المناعة وتقليل الالتهاب',
      'تقسيم الوجبات لتحمل أفضل للعلاج الكيميائي والإشعاعي',
      'معالجة الغثيان وفقدان الشهية',
    ],
    contraindications: [],
    monitoringRequirements: [
      'الوزن أسبوعياً',
      'ألبومين شهرياً',
      'كتلة العضلات',
      'تقييم جودة الحياة',
    ],
  },
  {
    id: 'autoimmune',
    category: 'autoimmune',
    phase: 'special_conditions',
    name: 'Autoimmune Disease Nutrition',
    nameAr: 'تغذية أمراض المناعة الذاتية',
    nutrientTargets: {
      calories: '25-30 kcal/kg',
      protein: 1.2,
      carbsPercent: 50,
      fatPercent: 30,
      fluid: '30 ml/kg',
      specialNutrients: ['أوميغا-3 2-3 غم/يوم', 'فيتامين د 2000 وحدة/يوم'],
    },
    guidelines: ['AAO Autoimmune Guidelines'],
    specialConsiderations: [
      'نظام غذائي مضاد للالتهاب (Anti-inflammatory Diet)',
      'أوميغا-3 لتقليل الالتهاب',
      'فيتامين د لتنظيم المناعة',
      'تجنب الأغذية المثبتة كمحفزات للمرض',
    ],
    contraindications: ['الأغذية المثيرة للحساسية حسب كل حالة'],
    monitoringRequirements: ['علامات الالتهاب شهرياً', 'فيتامين د شهرياً', 'الوزن شهرياً'],
  },
  {
    id: 'transplant',
    category: 'transplant',
    phase: 'special_conditions',
    name: 'Organ Transplant Nutrition',
    nameAr: 'تغذية زراعة الأعضاء',
    nutrientTargets: {
      calories: '30-35 kcal/kg',
      protein: 1.5,
      carbsPercent: 50,
      fatPercent: 30,
      fluid: '30 ml/kg',
      specialNutrients: ['بروتين عالي', 'فيتامين د'],
    },
    guidelines: ['AST Transplant Guidelines', 'ESPEN Transplant'],
    specialConsiderations: [
      'بروتين عالي للتعافي الجراحي وبناء الأنسجة',
      'تجنب العدوى الغذائية (غسل الخضار جيداً، طهي اللحوم جيداً)',
      'مراقبة تفاعل الأدوية المثبطة للمناعة مع الغذاء (ممنوع الجريب فروت)',
      'تجنب المكملات العشبية غير المعروفة',
    ],
    contraindications: ['الجريب فروت (تفاعل مع مثبطات الكالسينيورين)', 'المكملات العشبية غير المدروسة'],
    monitoringRequirements: [
      'وظائف العضو المزروع',
      'مستوى الأدوية المثبطة للمناعة',
      'الوزن أسبوعياً',
      'ألبومين شهرياً',
    ],
  },
];

export function registerAllProtocols(): void {
  const all: ClinicalProtocol[] = [
    ...healthyProtocols,
    ...pediatricProtocols,
    ...pregnancyProtocols,
    ...sportsProtocols,
    ...weightProtocols,
    ...chronicProtocols,
    ...criticalCareProtocols,
    ...specialProtocols,
  ];
  ProtocolRegistry.registerAll(all);
}
