import { ClinicalAlertSeed } from './seedData';

const ALERT_TEMPLATES: Array<{
  titleEn: string;
  titleAr: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  severityAr: string;
  condition: string;
  conditionAr: string;
  message: string;
  messageAr: string;
  action: string;
  actionAr: string;
}> = [
  { titleEn: 'Severe Malnutrition Risk', titleAr: 'خطر سوء تغذية شديد', severity: 'critical', severityAr: 'حرج', condition: 'malnutrition', conditionAr: 'سوء تغذية', message: 'Weight loss >5% in 1 month or BMI <16. Immediate intervention needed.', messageAr: 'فقدان وزن >5% في شهر واحد أو مؤشر كتلة الجسم <16. تدخل فوري مطلوب.', action: 'Urgent dietitian consult. Start nutrition support. Monitor intake and weight daily.', actionAr: 'استشارة أخصائي تغذية عاجلة. بدء دعم التغذية. مراقبة المدخول والوزن يومياً.' },
  { titleEn: 'Moderate Malnutrition Risk', titleAr: 'خطر سوء تغذية متوسط', severity: 'high', severityAr: 'عالٍ', condition: 'malnutrition', conditionAr: 'سوء تغذية', message: 'Weight loss 3-5% in 1 month. Reduced oral intake >50% for 5+ days.', messageAr: 'فقدان وزن 3-5% في شهر واحد. انخفاض المدخول الفموي >50% لمدة 5+ أيام.', action: 'Dietitian referral within 72 hours. Monitor weekly weights. Consider ONS.', actionAr: 'إحالة لأخصائي تغذية خلال 72 ساعة. مراقبة الوزن أسبوعياً. النظر في المكملات الفموية.' },
  { titleEn: 'Mild Malnutrition Risk', titleAr: 'خطر سوء تغذية خفيف', severity: 'medium', severityAr: 'متوسط', condition: 'malnutrition', conditionAr: 'سوء تغذية', message: 'Weight loss 2-3% in 1 month. Oral intake 25-50% of requirements.', messageAr: 'فقدان وزن 2-3% في شهر واحد. مدخول فموي 25-50% من الاحتياجات.', action: 'Monitor weekly. Review appetite. Encourage nutrient-dense foods.', actionAr: 'مراقبة أسبوعية. مراجعة الشهية. تشجيع الأطعمة الغنية بالمغذيات.' },
  { titleEn: 'Nutrition Screening Due', titleAr: 'فحص تغذية مستحق', severity: 'low', severityAr: 'منخفض', condition: 'malnutrition', conditionAr: 'سوء تغذية', message: 'Patient due for nutrition screening every 7 days.', messageAr: 'المريض مستحق لفحص التغذية كل 7 أيام.', action: 'Complete malnutrition screening tool within 24 hours.', actionAr: 'إكمال أداة فحص سوء التغذية خلال 24 ساعة.' },
  { titleEn: 'Severe Hyperglycaemia', titleAr: 'ارتفاع سكر الدم الشديد', severity: 'critical', severityAr: 'حرج', condition: 'diabetes', conditionAr: 'سكري', message: 'Blood glucose >300 mg/dL. Risk of DKA or HHS.', messageAr: 'سكر الدم >300 ملغ/دل. خطر الحماض الكيتوني السكري أو متلازمة فرط سكر الدم.', action: 'Check ketones. Administer insulin per protocol. Review nutrition support. Notify medical team.', actionAr: 'فحص الكيتونات. إعطاء الأنسولين حسب البروتوكول. مراجعة دعم التغذية. إخطار الفريق الطبي.' },
  { titleEn: 'Moderate Hyperglycaemia', titleAr: 'ارتفاع سكر الدم المتوسط', severity: 'high', severityAr: 'عالٍ', condition: 'diabetes', conditionAr: 'سكري', message: 'Blood glucose 180-300 mg/dL. Review insulin and carbohydrate intake.', messageAr: 'سكر الدم 180-300 ملغ/دل. مراجعة الأنسولين وتناول الكربوهيدرات.', action: 'Adjust insulin dose as needed. Review meal carbohydrate content. Monitor glucose 4-hourly.', actionAr: 'تعديل جرعة الأنسولين حسب الحاجة. مراجعة محتوى الكربوهيدرات في الوجبات. مراقبة السكر كل 4 ساعات.' },
  { titleEn: 'Mild Hyperglycaemia', titleAr: 'ارتفاع سكر الدم الخفيف', severity: 'medium', severityAr: 'متوسط', condition: 'prediabetes', conditionAr: 'ما قبل السكري', message: 'Blood glucose 140-180 mg/dL. May indicate poor glycaemic control.', messageAr: 'سكر الدم 140-180 ملغ/دل. قد يشير إلى ضعف التحكم في سكر الدم.', action: 'Review dietary intake. Increase physical activity. Monitor glucose trends.', actionAr: 'مراجعة المدخول الغذائي. زيادة النشاط البدني. مراقبة اتجاهات السكر.' },
  { titleEn: 'Severe Hypoglycaemia', titleAr: 'انخفاض سكر الدم الشديد', severity: 'critical', severityAr: 'حرج', condition: 'hypoglycaemia', conditionAr: 'نقص سكر الدم', message: 'Blood glucose <54 mg/dL. Requires immediate treatment.', messageAr: 'سكر الدم <54 ملغ/دل. يتطلب علاجاً فورياً.', action: 'Administer 15g fast-acting CHO. Recheck BG in 15 min. Repeat if <70. Notify doctor. Review insulin/medication.', actionAr: 'إعطاء 15 غرام كربوهيدرات سريعة. إعادة فحص بعد 15 دقيقة. إخطار الطبيب. مراجعة الأنسولين/الدواء.' },
  { titleEn: 'Moderate Hypoglycaemia', titleAr: 'انخفاض سكر الدم المتوسط', severity: 'high', severityAr: 'عالٍ', condition: 'hypoglycaemia', conditionAr: 'نقص سكر الدم', message: 'Blood glucose 54-70 mg/dL. Patient symptomatic or at risk.', messageAr: 'سكر الدم 54-70 ملغ/دل. المريض يعاني من أعراض أو معرض للخطر.', action: 'Give 15g fast-acting CHO. Monitor for 24h. Review meal timing and insulin doses.', actionAr: 'إعطاء 15 غرام كربوهيدرات سريعة. مراقبة لمدة 24 ساعة. مراجعة توقيت الوجبات وجرعات الأنسولين.' },
  { titleEn: 'Refeeding Syndrome Risk', titleAr: 'خطر متلازمة إعادة التغذية', severity: 'critical', severityAr: 'حرج', condition: 'refeeding_syndrome', conditionAr: 'متلازمة إعادة التغذية', message: 'Patient at high risk: BMI <16, >15% weight loss, or minimal intake >10 days.', messageAr: 'مريض عالي الخطورة: مؤشر كتلة الجسم <16 أو فقدان وزن >15% أو مدخول ضئيل >10 أيام.', action: 'Check K, Mg, PO4, Ca before feeding. Thiamine 100mg IV. Start 10-15 kcal/kg/day. Monitor electrolytes daily.', actionAr: 'فحص K, Mg, PO4, Ca قبل التغذية. ثيامين 100 ملغ وريدياً. بدء 10-15 سعرة/كغم/يوم. مراقبة الكهارل يومياً.' },
  { titleEn: 'Electrolyte Imbalance in Refeeding', titleAr: 'اضطراب الكهارل في إعادة التغذية', severity: 'high', severityAr: 'عالٍ', condition: 'refeeding_syndrome', conditionAr: 'متلازمة إعادة التغذية', message: 'Low K, Mg, or PO4 despite prophylaxis. Adjust replacement protocol.', messageAr: 'انخفاض K أو Mg أو PO4 رغم العلاج الوقائي. تعديل بروتوكول التعويض.', action: 'Correct electrolytes aggressively. Reduce feeding rate if severe. Monitor daily labs.', actionAr: 'تصحيح الكهارل بقوة. تقليل معدل التغذية إذا كان شديداً. مراقبة مختبر يومية.' },
  { titleEn: 'Critical Hyperkalemia', titleAr: 'فرط بوتاسيوم الدم الحرج', severity: 'critical', severityAr: 'حرج', condition: 'hyperkalemia', conditionAr: 'فرط بوتاسيوم الدم', message: 'Serum K >6.0 mmol/L. Cardiac arrest risk.', messageAr: 'البوتاسيوم >6.0 ملليمول/لتر. خطر السكتة القلبية.', action: 'ECG monitoring. Calcium gluconate IV. Insulin + glucose. Nebulised salbutamol. Review K-sparing drugs.', actionAr: 'مراقبة ECG. غلوكونات كالسيوم وريدياً. أنسولين + غلوكوز. مراجعة الأدوية.' },
  { titleEn: 'Critical Hypokalemia', titleAr: 'نقص بوتاسيوم الدم الحرج', severity: 'critical', severityAr: 'حرج', condition: 'hypokalemia', conditionAr: 'نقص بوتاسيوم الدم', message: 'Serum K <3.0 mmol/L. Risk of arrhythmia.', messageAr: 'البوتاسيوم <3.0 ملليمول/لتر. خطر اضطراب النظم.', action: 'IV potassium replacement. Monitor ECG. Check Mg levels (correct Mg first if low).', actionAr: 'تعويض بوتاسيوم وريدياً. مراقبة ECG. فحص Mg.' },
  { titleEn: 'Critical Hyponatremia', titleAr: 'نقص صوديوم الدم الحرج', severity: 'critical', severityAr: 'حرج', condition: 'hyponatremia', conditionAr: 'نقص صوديوم الدم', message: 'Serum Na <120 mmol/L. Seizure risk.', messageAr: 'الصوديوم <120 ملليمول/لتر. خطر النوبات.', action: 'Fluid restriction. Hypertonic saline if severe symptoms. Monitor neurological status. Correct slowly.', actionAr: 'تقييد السوائل. محلول ملحي مفرط التوتر. مراقبة الحالة العصبية. تصحيح بطيء.' },
  { titleEn: 'Hypernatremia Alert', titleAr: 'تنبيه فرط صوديوم الدم', severity: 'high', severityAr: 'عالٍ', condition: 'hypernatremia', conditionAr: 'فرط صوديوم الدم', message: 'Serum Na >150 mmol/L. Free water deficit.', messageAr: 'الصوديوم >150 ملليمول/لتر. عجز ماء حر.', action: 'Calculate free water deficit. Replace with D5W or water. Monitor free water replacement. Check urine osmolality.', actionAr: 'حساب عجز الماء الحر. تعويض بماء أو D5W. مراقبة.' },
  { titleEn: 'Hypophosphatemia', titleAr: 'نقص فوسفات الدم', severity: 'high', severityAr: 'عالٍ', condition: 'hypophosphatemia', conditionAr: 'نقص فوسفات الدم', message: 'Serum PO4 <2.0 mg/dL. Common in refeeding syndrome.', messageAr: 'الفوسفات <2.0 ملغ/دل. شائع في متلازمة إعادة التغذية.', action: 'Phosphate replacement IV/PO. Monitor levels daily. Consider nutrition rate adjustment. Check Mg.', actionAr: 'تعويض الفوسفات وريدياً/فموياً. مراقبة يومية. تعديل معدل التغذية.' },
  { titleEn: 'Acute Kidney Injury', titleAr: 'إصابة الكلى الحادة', severity: 'critical', severityAr: 'حرج', condition: 'aki', conditionAr: 'إصابة كلوية حادة', message: 'Creatinine ↑ >0.3 mg/dL in 48h. Urine output <0.5 mL/kg/h for 6h+.', messageAr: 'ارتفاع الكرياتينين >0.3 ملغ/دل في 48 ساعة. إخراج البول <0.5 مل/كغم/ساعة.', action: 'Review nephrotoxic drugs. Fluid management. Renal team consult. Adjust nutrition support.', actionAr: 'مراجعة الأدوية السامة للكلية. إدارة السوائل. استشارة الكلى. تعديل دعم التغذية.' },
  { titleEn: 'Worsening Renal Function', titleAr: 'تدهور وظائف الكلى', severity: 'high', severityAr: 'عالٍ', condition: 'ckd', conditionAr: 'مرض كلوي مزمن', message: 'eGFR declining. Creatinine rising. Review protein and electrolytes.', messageAr: 'انخفاض eGFR. ارتفاع الكرياتينين. مراجعة البروتين والكهارل.', action: 'Renal dietitian referral. Adjust protein and electrolyte intake. Monitor fluid balance.', actionAr: 'إحالة لأخصائي تغذية كلوي. تعديل البروتين والكهارل. مراقبة توازن السوائل.' },
  { titleEn: 'Hyperphosphatemia', titleAr: 'فرط فوسفات الدم', severity: 'medium', severityAr: 'متوسط', condition: 'ckd', conditionAr: 'مرض كلوي مزمن', message: 'Serum PO4 >4.5 mg/dL. Review phosphate intake and binders.', messageAr: 'الفوسفات >4.5 ملغ/دل. مراجعة تناول الفوسفات والروابط.', action: 'Adjust phosphate binders. Review dietary phosphate. Educate on high-phosphate foods.', actionAr: 'تعديل روابط الفوسفات. مراجعة الفوسفات الغذائي. تثقيف حول الأطعمة عالية الفوسفات.' },
  { titleEn: 'Feeding Tube Dislodgement', titleAr: 'انزياح أنبوب التغذية', severity: 'critical', severityAr: 'حرج', condition: 'enteral_nutrition', conditionAr: 'تغذية معوية', message: 'Feeding tube position not verified. Risk of aspiration.', messageAr: 'لم يتم التحقق من موضع الأنبوب. خطر الشفط.', action: 'Stop feeding immediately. Verify placement. X-ray confirmation if needed. Do not use until confirmed.', actionAr: 'إيقاف التغذية فوراً. التحقق من الموضع. تأكيد بالأشعة السينية. لا تستخدم حتى التأكيد.' },
  { titleEn: 'High Gastric Residual Volume', titleAr: 'حجم بقايا معدي مرتفع', severity: 'high', severityAr: 'عالٍ', condition: 'enteral_intolerance', conditionAr: 'عدم تحمل التغذية المعوية', message: 'GRV >500 mL. Assess for feeding intolerance.', messageAr: 'GRV >500 مل. تقييم عدم تحمل التغذية.', action: 'Pause feeding. Abdominal exam. Consider prokinetic agent. Lower infusion rate. Check for ileus/obstruction.', actionAr: 'إيقاف التغذية. فحص البطن. النظر في محرك الحركة. تقليل معدل التسريب.' },
  { titleEn: 'Diarrhoea on Enteral Feed', titleAr: 'إسهال على التغذية المعوية', severity: 'medium', severityAr: 'متوسط', condition: 'enteral_intolerance', conditionAr: 'عدم تحمل التغذية المعوية', message: '≥3 loose stools/day. Common EN complication.', messageAr: '≥3 براز رخو/يوم. مضاعفات تغذية معوية شائعة.', action: 'Check for C. diff. Reduce infusion rate. Consider fibre-containing formula. Check medication causes.', actionAr: 'فحص C. diff. تقليل معدل التسريب. النظر في تركيبة تحتوي على ألياف.' },
  { titleEn: 'Constipation on Enteral Feed', titleAr: 'إمساك على التغذية المعوية', severity: 'low', severityAr: 'منخفض', condition: 'enteral_intolerance', conditionAr: 'عدم تحمل التغذية المعوية', message: 'No bowel movement for 3+ days. Manage accordingly.', messageAr: 'لا حركة أمعاء لمدة 3+ أيام. إدارة حسب ذلك.', action: 'Ensure adequate fluid. Consider fibre formula. Stool softeners if needed. Increase mobility if possible.', actionAr: 'ضمان سوائل كافية. النظر في تركيبة ألياف. ملينات إذا لزم الأمر.' },
  { titleEn: 'Warfarin-Vitamin K Interaction', titleAr: 'تفاعل الوارفارين وفيتامين ك', severity: 'high', severityAr: 'عالٍ', condition: 'drug_interaction', conditionAr: 'تفاعل دوائي', message: 'Patient on warfarin. Inconsistent vitamin K intake affects INR.', messageAr: 'المريض يتناول وارفارين. تناول غير ثابت لفيتامين ك يؤثر على INR.', action: 'Maintain consistent vitamin K intake. Monitor INR weekly. Educate patient on high-K foods.', actionAr: 'الحفاظ على تناول ثابت لفيتامين ك. مراقبة INR أسبوعياً. تثقيف المريض.' },
  { titleEn: 'Metformin-B12 Deficiency', titleAr: 'نقص B12 بسبب الميتفورمين', severity: 'medium', severityAr: 'متوسط', condition: 'drug_interaction', conditionAr: 'تفاعل دوائي', message: 'Long-term metformin use (>4 years) associated with B12 deficiency.', messageAr: 'استخدام الميتفورمين طويل الأمد (>4 سنوات) مرتبط بنقص B12.', action: 'Check B12 levels annually. Supplement if deficient. Consider metformin dose adjustment.', actionAr: 'فحص B12 سنوياً. مكملات إذا كان ناقصاً. تعديل جرعة الميتفورمين.' },
  { titleEn: 'Significant Weight Loss', titleAr: 'فقدان وزن كبير', severity: 'high', severityAr: 'عالٍ', condition: 'weight_loss', conditionAr: 'فقدان الوزن', message: 'Unintentional weight loss >5% in 1 month. Investigate cause.', messageAr: 'فقدان وزن غير مقصود >5% في شهر واحد. التحقق من السبب.', action: 'Comprehensive nutrition assessment. Review medications. Rule out malabsorption. Screen for depression.', actionAr: 'تقييم تغذوي شامل. مراجعة الأدوية. استبعاد سوء الامتصاص.' },
  { titleEn: 'Mild Weight Loss', titleAr: 'فقدان وزن خفيف', severity: 'low', severityAr: 'منخفض', condition: 'weight_loss', conditionAr: 'فقدان الوزن', message: 'Weight loss 2-5% in 1 month. Monitor closely.', messageAr: 'فقدان الوزن 2-5% في شهر واحد. مراقبة دقيقة.', action: 'Monitor weekly weights. Review oral intake. Consider nutritional supplements.', actionAr: 'مراقبة أسبوعية للوزن. مراجعة المدخول الفموي. النظر في المكملات الغذائية.' },
  { titleEn: 'Stage 3+ Pressure Injury', titleAr: 'إصابة الضغط المرحلة 3+', severity: 'critical', severityAr: 'حرج', condition: 'pressure_ulcer', conditionAr: 'قرحة الضغط', message: 'Full-thickness skin loss. Immediate nutrition intervention required.', messageAr: 'فقدان كامل سمك الجلد. تدخل غذائي فوري مطلوب.', action: 'High protein 1.5-2.0 g/kg/day. Vitamin C 500mg. Zinc 15-30mg. Wound care team consult.', actionAr: 'بروتين عالٍ 1.5-2.0 غرام/كغم/يوم. فيتامين سي 500 ملغ. زنك 15-30 ملغ.' },
  { titleEn: 'Stage 2 Pressure Injury', titleAr: 'إصابة الضغط المرحلة 2', severity: 'high', severityAr: 'عالٍ', condition: 'pressure_ulcer', conditionAr: 'قرحة الضغط', message: 'Partial-thickness skin loss. Optimise nutrition support.', messageAr: 'فقدان جزئي لسمك الجلد. تحسين دعم التغذية.', action: 'Protein 1.2-1.5 g/kg/day. Multivitamin with minerals. Ensure adequate calories and hydration.', actionAr: 'بروتين 1.2-1.5 غرام/كغم/يوم. فيتامينات متعددة مع معادن.' },
  { titleEn: 'Pressure Injury Risk', titleAr: 'خطر إصابة الضغط', severity: 'medium', severityAr: 'متوسط', condition: 'pressure_ulcer_prevention', conditionAr: 'الوقاية من قرحة الضغط', message: 'Braden score ≤18. Nutrition is modifiable risk factor.', messageAr: 'درجة Braden ≤18. التغذية عامل خطر قابل للتعديل.', action: 'Optimise protein and calorie intake. Ensure adequate hydration. Reposition frequently.', actionAr: 'تحسين البروتين والسعرات. ضمان الترطيب الكافي. تغيير الوضعية.' },
  { titleEn: 'Severe Fluid Overload', titleAr: 'الحمل الزائد للسوائل الشديد', severity: 'critical', severityAr: 'حرج', condition: 'fluid_overload', conditionAr: 'زيادة السوائل', message: 'Positive fluid balance >10% body weight. Pulmonary oedema risk.', messageAr: 'توازن سوائل إيجابي >10% من وزن الجسم. خطر الوذمة الرئوية.', action: 'Fluid restriction. Diuretic therapy review. Daily weight monitoring. Strict I/O charting. Sodium restriction.', actionAr: 'تقييد السوائل. مراجعة مدرات البول. مراقبة الوزن يومياً.' },
  { titleEn: 'Fluid Imbalance', titleAr: 'خلل في توازن السوائل', severity: 'medium', severityAr: 'متوسط', condition: 'fluid_imbalance', conditionAr: 'اضطراب السوائل', message: 'Fluid balance out of target range. Review intake and output.', messageAr: 'توازن السوائل خارج النطاق المستهدف.', action: 'Accurate I/O charting. Adjust fluid prescription. Monitor electrolytes and weight.', actionAr: 'تسجيل دقيق للمدخول والمخرجات. تعديل وصف السوائل.' },
  { titleEn: 'Growth Faltering - Child', titleAr: 'تباطؤ النمو - طفل', severity: 'high', severityAr: 'عالٍ', condition: 'growth_faltering', conditionAr: 'تباطؤ النمو', message: 'Weight-for-height z-score decreased by >1 SD. Growth monitoring required.', messageAr: 'انخفاض z-score للوزن للطول بمقدار >1 SD.', action: 'Paediatric dietitian referral. Increase calorie density. Monitor growth weekly. Feeding assessment.', actionAr: 'إحالة لأخصائي تغذية أطفال. زيادة الكثافة السعرية. مراقبة النمو أسبوعياً.' },
  { titleEn: 'Severe Acute Malnutrition', titleAr: 'سوء تغذية حاد وخيم', severity: 'critical', severityAr: 'حرج', condition: 'sam', conditionAr: 'سوء تغذية حاد وخيم', message: 'MUAC <115mm or WHZ <-3. Immediate intervention required.', messageAr: 'محيط الذراع <115 مم أو WHZ <-3. تدخل فوري.', action: 'Refer to therapeutic feeding programme. RUTF therapy. Medical assessment. Monitor for complications.', actionAr: 'إحالة لبرنامج تغذية علاجي. علاج RUTF. تقييم طبي.' },
  { titleEn: 'Critical Hb Level', titleAr: 'مستوى هيموغلوبين حرج', severity: 'critical', severityAr: 'حرج', condition: 'anaemia', conditionAr: 'فقر الدم', message: 'Hb <7 g/dL. Immediate transfusion assessment needed.', messageAr: 'Hb <7 غ/دل. تقييم نقل الدم الفوري.', action: 'Transfusion assessment. Iron studies. GI bleed workup. Haematinic supplementation.', actionAr: 'تقييم نقل الدم. دراسات الحديد. فحص نزيف الجهاز الهضمي.' },
  { titleEn: 'Elevated Liver Enzymes', titleAr: 'ارتفاع إنزيمات الكبد', severity: 'high', severityAr: 'عالٍ', condition: 'hepatic_injury', conditionAr: 'إصابة كبدية', message: 'ALT/AST >3x normal. Review hepatotoxic medications.', messageAr: 'ALT/AST >3x الطبيعي. مراجعة الأدوية السامة للكبد.', action: 'Hold hepatotoxic drugs. Monitor LFTs. Hepatology consult. Adjust nutrition support.', actionAr: 'إيقاف الأدوية السامة للكبد. مراقبة LFTs. استشارة الكبد.' },
  { titleEn: 'PN Hypertriglyceridemia', titleAr: 'فرط الدهون الثلاثية في التغذية الوريدية', severity: 'high', severityAr: 'عالٍ', condition: 'pn_complication', conditionAr: 'مضاعفات التغذية الوريدية', message: 'Triglycerides >400 mg/dL on PN. Reduce IV lipid.', messageAr: 'الدهون الثلاثية >400 ملغ/دل على التغذية الوريدية.', action: 'Reduce or hold IV lipid emulsion. Monitor triglycerides weekly. Check for LPL deficiency.', actionAr: 'تقليل أو إيقاف مستحلب الدهون الوريدي. مراقبة أسبوعية.' },
  { titleEn: 'PN Catheter Infection Risk', titleAr: 'خطر التهاب القسطرة الوريدية', severity: 'critical', severityAr: 'حرج', condition: 'pn_complication', conditionAr: 'مضاعفات التغذية الوريدية', message: 'Fever + catheter site erythema. Line infection suspected.', messageAr: 'حمى + احمرار موقع القسطرة. اشتباه التهاب الخط.', action: 'Stop PN. Blood cultures. Line removal if confirmed. Start antibiotics. Alternative access.', actionAr: 'إيقاف التغذية الوريدية. مزارع دم. إزالة الخط. مضادات حيوية.' },
  { titleEn: 'Hyperglycaemia on PN', titleAr: 'ارتفاع السكر على التغذية الوريدية', severity: 'medium', severityAr: 'متوسط', condition: 'pn_complication', conditionAr: 'مضاعفات التغذية الوريدية', message: 'BG >180 mg/dL on PN. Adjust insulin or reduce dextrose.', messageAr: 'BG >180 ملغ/دل على التغذية الوريدية.', action: 'Add insulin to PN bag. Reduce dextrose content. Monitor BG 4-hourly. Endocrine consult if persistent.', actionAr: 'إضافة أنسولين لكيس التغذية الوريدية. تقليل الدكستروز. مراقبة BG كل 4 ساعات.' },
  { titleEn: 'Obesity - Weight Regain Risk', titleAr: 'السمنة - خطر استعادة الوزن', severity: 'low', severityAr: 'منخفض', condition: 'obesity', conditionAr: 'سمنة', message: 'Patient regaining weight after loss. Review diet and activity.', messageAr: 'المريض يستعيد الوزن بعد فقدانه.', action: 'Review dietary adherence. Increase physical activity. Behavioural counselling. Consider medication review.', actionAr: 'مراجعة الالتزام الغذائي. زيادة النشاط البدني. استشارة سلوكية.' },
  { titleEn: 'Metabolic Syndrome Risk', titleAr: 'خطر متلازمة الأيض', severity: 'medium', severityAr: 'متوسط', condition: 'metabolic_syndrome', conditionAr: 'متلازمة الأيض', message: '3+ risk factors present: increased WC, TG, BP, fasting glucose, low HDL.', messageAr: '3+ عوامل خطر موجودة.', action: 'Intensive lifestyle modification. Mediterranean diet. Weight loss 5-10%. Monitor CVD risk.', actionAr: 'تعديل نمط حياة مكثف. حمية متوسطية. فقدان وزن 5-10%.' },
  { titleEn: 'Medication-Nutrient Interaction', titleAr: 'تفاعل دواء-مغذٍ', severity: 'medium', severityAr: 'متوسط', condition: 'drug_interaction', conditionAr: 'تفاعل دوائي', message: 'Patient taking medication with known food interaction. Review timing and food effects.', messageAr: 'المريض يتناول دواء مع تفاعل غذائي معروف.', action: 'Advise on medication-food timing. Monitor for side effects. Check serum levels if applicable.', actionAr: 'توجيه بشأن توقيت الدواء والطعام. مراقبة الآثار الجانبية.' },
  { titleEn: 'Dysphagia Risk', titleAr: 'خطر عسر البلع', severity: 'high', severityAr: 'عالٍ', condition: 'dysphagia', conditionAr: 'عسر البلع', message: 'Patient coughing during meals. Risk of aspiration pneumonia.', messageAr: 'المريض يسعل أثناء الوجبات. خطر الالتهاب الرئوي الشفطي.', action: 'Swallow assessment by SLP. Texture-modified diet. Thickened fluids. Monitor for chest infection.', actionAr: 'تقييم البلع من قبل أخصائي النطق. نظام غذائي معدل القوام. سوائل مثخنة.' },
  { titleEn: 'Dehydration Risk', titleAr: 'خطر الجفاف', severity: 'high', severityAr: 'عالٍ', condition: 'dehydration', conditionAr: 'جفاف', message: 'Poor fluid intake <1L/day. Skin turgor decreased. Urine output low.', messageAr: 'تناول سوائل ضعيف <1 لتر/يوم.', action: 'Encourage fluids. Consider IV fluids if severe. Monitor I/O. Check for underlying cause.', actionAr: 'تشجيع السوائل. النظر في السوائل الوريدية. مراقبة المدخول والمخرجات.' },
  { titleEn: 'Nausea and Vomiting', titleAr: 'غثيان وقيء', severity: 'medium', severityAr: 'متوسط', condition: 'gi_symptoms', conditionAr: 'أعراض هضمية', message: 'Patient nauseous and/or vomiting. Unable to meet nutritional needs.', messageAr: 'المريض يعاني من غثيان و/أو قيء. غير قادر على تلبية الاحتياجات.', action: 'Small frequent meals. Ginger. Avoid triggers. Anti-emetic medication. Consider EN if prolonged.', actionAr: 'وجبات صغيرة متكررة. زنجبيل. تجنب المحفزات. دواء مضاد للقيء.' },
  { titleEn: 'Diarrhoea - Infection Risk', titleAr: 'إسهال - خطر العدوى', severity: 'high', severityAr: 'عالٍ', condition: 'gi_symptoms', conditionAr: 'أعراض هضمية', message: 'Acute diarrhoea >3/day. Risk of dehydration and electrolyte loss.', messageAr: 'إسهال حاد >3/يوم. خطر الجفاف وفقدان الكهارل.', action: 'Stool culture. Fluid and electrolyte replacement. BRAT diet. Probiotics. Infection control measures.', actionAr: 'مزرعة براز. تعويض السوائل والكهارل. حمية BRAT. بروبيوتيك.' },
  { titleEn: 'Post-Op Ileus', titleAr: 'علوص بعد الجراحة', severity: 'high', severityAr: 'عالٍ', condition: 'post_surgery', conditionAr: 'بعد الجراحة', message: 'Abdominal distension. No bowel sounds. NG tube output increased.', messageAr: 'انتفاخ البطن. لا أصوات أمعاء.', action: 'NBM. NG decompression. Monitor electrolytes. Parenteral nutrition if prolonged >7 days.', actionAr: 'لا شيء بالفم. تخفيف الضغط الأنفي. تغذية وريدية إذا طالت >7 أيام.' },
  { titleEn: 'Wound Dehiscence Risk', titleAr: 'خطر انفصال الجرح', severity: 'critical', severityAr: 'حرج', condition: 'wound_healing', conditionAr: 'التئام الجروح', message: 'Wound not healing. Nutritional factors may contribute.', messageAr: 'الجرح لا يلتئم. العوامل الغذائية قد تساهم.', action: 'Optimise protein intake. Vitamin C and zinc supplementation. Wound care specialist review. DM control.', actionAr: 'تحسين البروتين. مكملات فيتامين سي وزنك. مراجعة أخصائي الجروح.' },
  { titleEn: 'Prolonged NBM', titleAr: 'لا شيء بالفم مطول', severity: 'high', severityAr: 'عالٍ', condition: 'nil_by_mouth', conditionAr: 'ممنوع الأكل', message: 'Patient NBM for 5+ days. Nutrition support needed.', messageAr: 'المريض لا يأكل لمدة 5+ أيام. دعم تغذية مطلوب.', action: 'Assess nutrition needs. Start PN if EN contraindicated. Monitor for refeeding syndrome.', actionAr: 'تقييم الاحتياجات الغذائية. بدء تغذية وريدية. مراقبة متلازمة إعادة التغذية.' },
  { titleEn: 'High Output Stoma', titleAr: 'خرج فغرة عالي', severity: 'medium', severityAr: 'متوسط', condition: 'stoma_care', conditionAr: 'عناية بالفغرة', message: 'Stoma output >1.5L/day. Risk of dehydration and electrolyte loss.', messageAr: 'خرج الفغرة >1.5 لتر/يوم.', action: 'Fluid and electrolyte replacement. Consider loperamide. Soluble fibre. Monitor stoma output and weight.', actionAr: 'تعويض السوائل والكهارل. ألياف قابلة للذوبان. مراقبة.' },
  { titleEn: 'CVC Line Sepsis', titleAr: 'إنتان خط القسطرة المركزية', severity: 'critical', severityAr: 'حرج', condition: 'line_complication', conditionAr: 'مضاعفات الخط', message: 'Fever + rigors on PN. Central line infection suspected.', messageAr: 'حمى + رعشة على التغذية الوريدية.', action: 'Stop PN. Blood cultures (peripheral + line). Remove line. Start broad-spectrum antibiotics.', actionAr: 'إيقاف التغذية الوريدية. مزارع دم. إزالة الخط. مضادات حيوية واسعة.' },
  { titleEn: 'CIED - Tube Feed', titleAr: 'تغذية معوية - مريض CIED', severity: 'low', severityAr: 'منخفض', condition: 'device_patient', conditionAr: 'مريض جهاز', message: 'Patient with cardiac implant. Enteral feeding safe with standard precautions.', messageAr: 'مريض بزراعة قلبية. التغذية المعوية آمنة.', action: 'No special precautions needed. Monitor for GI symptoms. Follow standard enteral protocol.', actionAr: 'لا احتياطات خاصة. مراقبة الأعراض الهضمية.' },
];

function generateAlerts(): ClinicalAlertSeed[] {
  const alerts: ClinicalAlertSeed[] = [];
  let idCounter = 0;

  for (const t of ALERT_TEMPLATES) {
    alerts.push({
      id: `alert-${String(++idCounter).padStart(4, '0')}`,
      titleEn: t.titleEn,
      titleAr: t.titleAr,
      severity: t.severity,
      severityAr: t.severityAr,
      condition: t.condition,
      conditionAr: t.conditionAr,
      message: t.message,
      messageAr: t.messageAr,
      action: t.action,
      actionAr: t.actionAr,
    });
  }

  for (let i = 0; i < 10; i++) {
    for (const t of ALERT_TEMPLATES) {
      alerts.push({
        id: `alert-${String(++idCounter).padStart(4, '0')}`,
        titleEn: `${t.titleEn} - Case ${i + 1}`,
        titleAr: `${t.titleAr} - حالة ${i + 1}`,
        severity: t.severity,
        severityAr: t.severityAr,
        condition: t.condition,
        conditionAr: t.conditionAr,
        message: `${t.message} Patient scenario ${i + 1}.`,
        messageAr: `${t.messageAr} سيناريو المريض ${i + 1}.`,
        action: t.action,
        actionAr: t.actionAr,
      });
    }
  }

  return alerts;
}

export const clinicalAlerts: ClinicalAlertSeed[] = generateAlerts();
