import { ClinicalGuidelineSeed } from './seedData';

const CONDITIONS: Array<{
  condition: string;
  titleEn: string;
  titleAr: string;
  category: string;
  recommendations: string;
  recommendationsAr: string;
  evidenceLevel: string;
  source: string;
}> = [
  { condition: 'diabetes_mellitus', titleEn: 'Medical Nutrition Therapy for Diabetes', titleAr: 'العلاج الغذائي الطبي لمرضى السكري', category: 'nutrition_therapy', recommendations: 'Individualized MNT for all adults with diabetes. Carbohydrate intake should emphasize nutrient-dense sources. Limit saturated fat to <10% of total energy.', recommendationsAr: 'العلاج الغذائي الطبي الفردي لجميع البالغين المصابين بداء السكري. يجب أن يركز تناول الكربوهيدرات على المصادر الغنية بالمغذيات. الحد من الدهون المشبعة إلى أقل من 10٪ من إجمالي الطاقة.', evidenceLevel: 'high', source: 'ADA Standards of Care 2024' },
  { condition: 'gestational_diabetes', titleEn: 'Gestational Diabetes Nutrition', titleAr: 'تغذية سكري الحمل', category: 'nutrition_therapy', recommendations: 'All women with GDM should receive MNT. Blood glucose monitoring 4 times daily. Minimum 175g carbohydrate daily.', recommendationsAr: 'جميع النساء المصابات بسكري الحمل يجب أن يحصلن على علاج غذائي طبي. مراقبة سكر الدم 4 مرات يومياً. 175 غرام كربوهيدرات يومياً كحد أدنى.', evidenceLevel: 'high', source: 'ADA Standards of Care 2024' },
  { condition: 'diabetes_type_1', titleEn: 'Carbohydrate Counting for T1D', titleAr: 'حساب الكربوهيدرات للسكري النوع الأول', category: 'carbohydrate_management', recommendations: 'Advanced carbohydrate counting recommended. Insulin-to-carbohydrate ratio should be individualized. CGM recommended for all on intensive insulin.', recommendationsAr: 'حساب الكربوهيدرات المتقدم موصى به. يجب تخصيص نسبة الأنسولين إلى الكربوهيدرات. المراقبة المستمرة للغلوكوز موصى بها.', evidenceLevel: 'high', source: 'ISPAD 2022' },
  { condition: 'diabetes_mellitus', titleEn: 'Diabetes Pre-Meal Insulin Dosing', titleAr: 'جرعات الأنسولين قبل الوجبات للسكري', category: 'insulin_management', recommendations: 'Administer rapid-acting insulin 15-20 minutes before meals based on carbohydrate content.', recommendationsAr: 'إعطاء الأنسولين سريع المفعول قبل 15-20 دقيقة من الوجبات بناءً على محتوى الكربوهيدرات.', evidenceLevel: 'high', source: 'ADA Standards of Care 2024' },
  { condition: 'chronic_kidney_disease', titleEn: 'Dietary Management of CKD', titleAr: 'الإدارة الغذائية لأمراض الكلى المزمنة', category: 'renal_nutrition', recommendations: 'Protein restriction 0.6-0.8 g/kg/day for non-dialysis CKD. Sodium <2g/day. Potassium individualized. Phosphate restriction 800-1000mg/day.', recommendationsAr: 'تقييد البروتين 0.6-0.8 غرام/كغم/يوم لمرضى الكلى المزمن غير الخاضعين للغسيل. صوديوم أقل من 2 غرام/يوم. تخصيص البوتاسيوم. تقييد الفوسفات 800-1000 ملغ/يوم.', evidenceLevel: 'high', source: 'KDIGO 2024' },
  { condition: 'haemodialysis', titleEn: 'Haemodialysis Nutrition', titleAr: 'التغذية في غسيل الكلى الدموي', category: 'renal_nutrition', recommendations: 'Protein 1.2-1.4 g/kg/day. Energy 30-35 kcal/kg/day. Sodium <2g/day. Fluid restriction 500-1000ml + urine output.', recommendationsAr: 'بروتين 1.2-1.4 غرام/كغم/يوم. طاقة 30-35 سعرة/كغم/يوم. صوديوم أقل من 2 غرام/يوم. تقييد السوائل 500-1000 مل + إخراج البول.', evidenceLevel: 'high', source: 'KDOQI 2020' },
  { condition: 'peritoneal_dialysis', titleEn: 'Peritoneal Dialysis Nutrition', titleAr: 'التغذية في غسيل الكلى البريتوني', category: 'renal_nutrition', recommendations: 'Protein 1.2-1.5 g/kg/day. Energy 25-35 kcal/kg/day including dialysate glucose. Sodium restriction 1.5-2g/day.', recommendationsAr: 'بروتين 1.2-1.5 غرام/كغم/يوم. طاقة 25-35 سعرة/كغم/يوم. تقييد الصوديوم 1.5-2 غرام/يوم.', evidenceLevel: 'high', source: 'KDOQI 2020' },
  { condition: 'critical_illness', titleEn: 'ICU Nutrition Support', titleAr: 'دعم التغذية في العناية المركزة', category: 'icu_nutrition', recommendations: 'Screen all ICU patients within 24-48h. Initiate EN within 24-48h. Energy 25-30 kcal/kg/day. Protein 1.2-2.0 g/kg/day.', recommendationsAr: 'فحص جميع مرضى العناية المركزة خلال 24-48 ساعة. بدء التغذية المعوية خلال 24-48 ساعة. طاقة 25-30 سعرة/كغم/يوم. بروتين 1.2-2.0 غرام/كغم/يوم.', evidenceLevel: 'high', source: 'ASPEN/SCCM 2021' },
  { condition: 'icu_hyperglycaemia', titleEn: 'ICU Glycemic Control', titleAr: 'التحكم في سكر الدم في العناية المركزة', category: 'icu_nutrition', recommendations: 'Maintain BG 140-180 mg/dL. Avoid intensive insulin targeting <110 mg/dL. Monitor BG every 4h on EN/PN.', recommendationsAr: 'الحفاظ على سكر الدم 140-180 ملغ/دل. تجنب الأنسولين المكثف المستهدف أقل من 110 ملغ/دل. مراقبة كل 4 ساعات.', evidenceLevel: 'high', source: 'SSC Guidelines 2024' },
  { condition: 'heart_failure', titleEn: 'Heart Failure Nutrition', titleAr: 'التغذية لفشل القلب', category: 'cardiac_nutrition', recommendations: 'Sodium <2g/day in symptomatic HF. Fluid restriction 1.5-2L/day in severe overload. Daily weight monitoring.', recommendationsAr: 'صوديوم أقل من 2 غرام/يوم في فشل القلب المصحوب بأعراض. تقييد السوائل 1.5-2 لتر/يوم. مراقبة الوزن يومياً.', evidenceLevel: 'high', source: 'ACC/AHA 2022' },
  { condition: 'hypertension', titleEn: 'DASH Diet for Hypertension', titleAr: 'حمية داش لارتفاع ضغط الدم', category: 'cardiac_nutrition', recommendations: 'Adopt DASH pattern rich in fruits, vegetables, whole grains, low-fat dairy. Sodium <1.5g/day. Potassium 3500-5000mg/day.', recommendationsAr: 'اعتماد حمية داش الغنية بالفواكه والخضروات والحبوب الكاملة ومنتجات الألبان قليلة الدسم. صوديوم أقل من 1.5 غرام/يوم. بوتاسيوم 3500-5000 ملغ/يوم.', evidenceLevel: 'high', source: 'ACC/AHA 2017' },
  { condition: 'hyperlipidaemia', titleEn: 'Dietary Management of Hyperlipidemia', titleAr: 'الإدارة الغذائية لفرط شحميات الدم', category: 'cardiac_nutrition', recommendations: 'Mediterranean diet rich in olive oil, nuts, fish. Saturated fat <7% total calories. Plant stanols/sterols 2g/day.', recommendationsAr: 'نظام غذائي متوسطي غني بزيت الزيتون والمكسرات والأسماك. دهون مشبعة أقل من 7٪. ستانول/ستيرول نباتي 2 غرام/يوم.', evidenceLevel: 'high', source: 'ACC/AHA 2022' },
  { condition: 'liver_cirrhosis', titleEn: 'Cirrhosis Nutrition', titleAr: 'التغذية لتليف الكبد', category: 'hepatic_nutrition', recommendations: 'Energy 25-35 kcal/kg/day. Protein 1.2-1.5 g/kg/day even in encephalopathy. Sodium <2g/day for ascites. Small frequent meals.', recommendationsAr: 'طاقة 25-35 سعرة/كغم/يوم. بروتين 1.2-1.5 غرام/كغم/يوم حتى في الاعتلال الدماغي. صوديوم أقل من 2 غرام/يوم للاستسقاء. وجبات صغيرة متكررة.', evidenceLevel: 'high', source: 'EASL 2019' },
  { condition: 'cancer', titleEn: 'Cancer Nutrition Support', titleAr: 'دعم التغذية لمرضى السرطان', category: 'oncology_nutrition', recommendations: 'Screen all cancer patients with PG-SGA. Energy 25-30 kcal/kg/day. Protein 1.2-2.0 g/kg/day. Omega-3 (EPA) may stabilize weight.', recommendationsAr: 'فحص جميع مرضى السرطان باستخدام PG-SGA. طاقة 25-30 سعرة/كغم/يوم. بروتين 1.2-2.0 غرام/كغم/يوم. أوميغا-3 قد تثبت الوزن.', evidenceLevel: 'high', source: 'ESPEN 2021' },
  { condition: 'acute_pancreatitis', titleEn: 'Acute Pancreatitis Nutrition', titleAr: 'التغذية لالتهاب البنكرياس الحاد', category: 'gi_nutrition', recommendations: 'Early EN within 24-48h in predicted severe pancreatitis. NG or NJ route both acceptable. Semi-elemental formula if tolerated.', recommendationsAr: 'تغذية معوية مبكرة خلال 24-48 ساعة. طريق أنفي معدي أو صائمي مقبول. تركيبة شبه أولية.', evidenceLevel: 'high', source: 'IAP/APA 2023' },
  { condition: 'paediatric_malnutrition', titleEn: 'Paediatric Malnutrition Management', titleAr: 'إدارة سوء التغذية عند الأطفال', category: 'paediatric_nutrition', recommendations: 'Use WHO growth standards. SAM defined as WHZ < -3 SD or MUAC <115mm. RUTF for uncomplicated SAM. Exclusive breastfeeding 6 months.', recommendationsAr: 'استخدام معايير النمو لمنظمة الصحة العالمية. سوء التغذية الحاد الوخيم: الوزن للطول أقل من -3 SD. الغذاء العلاجي الجاهز. رضاعة طبيعية حصرية 6 أشهر.', evidenceLevel: 'high', source: 'WHO 2023' },
  { condition: 'obesity', titleEn: 'Obesity Nutrition Management', titleAr: 'إدارة التغذية للسمنة', category: 'weight_management', recommendations: '500-1000 kcal/day deficit for 0.5-1 kg/week weight loss. 150-300 min/week moderate exercise. Consider anti-obesity medication if BMI >30.', recommendationsAr: 'عجز 500-1000 سعرة/يوم لفقدان 0.5-1 كغم/أسبوع. 150-300 دقيقة/أسبوع تمرين. النظر في أدوية السمنة.', evidenceLevel: 'high', source: 'AACE/ACE 2022' },
  { condition: 'pressure_ulcer', titleEn: 'Pressure Injury Nutrition', titleAr: 'التغذية لإصابات الضغط', category: 'wound_care', recommendations: 'Protein 1.5-2.0 g/kg/day for stage 3+ injuries. Vitamin C 500mg/day. Zinc supplementation. Adequate hydration.', recommendationsAr: 'بروتين 1.5-2.0 غرام/كغم/يوم للمرحلة 3+. فيتامين سي 500 ملغ/يوم. مكملات الزنك. ترطيب كاف.', evidenceLevel: 'high', source: 'NPUAP/EPUAP 2019' },
  { condition: 'refeeding_syndrome', titleEn: 'Refeeding Syndrome Prevention', titleAr: 'الوقاية من متلازمة إعادة التغذية', category: 'icu_nutrition', recommendations: 'Identify at-risk patients. Check K, Mg, PO4 before feeding. Thiamine 100mg IV. Start 10-15 kcal/kg/day. Monitor electrolytes daily.', recommendationsAr: 'تحديد المرضى المعرضين للخطر. فحص K, Mg, PO4 قبل التغذية. ثيامين 100 ملغ وريدياً. بدء 10-15 سعرة/كغم/يوم. مراقبة يومية.', evidenceLevel: 'high', source: 'ASPEN 2021' },
  { condition: 'short_bowel', titleEn: 'Short Bowel Syndrome Nutrition', titleAr: 'التغذية لمتلازمة الأمعاء القصيرة', category: 'gi_nutrition', recommendations: 'Oral diet + PN/IV fluids as needed. High complex carbohydrates. Soluble fibre for stool consistency. Fluid and electrolyte monitoring.', recommendationsAr: 'نظام غذائي فموي + تغذية وريدية/سوائل حسب الحاجة. كربوهيدرات معقدة عالية. ألياف قابلة للذوبان. مراقبة السوائل والكهارل.', evidenceLevel: 'moderate', source: 'ESPEN 2022' },
  { condition: 'malabsorption', titleEn: 'Malabsorption Nutrition Support', titleAr: 'دعم التغذية لسوء الامتصاص', category: 'gi_nutrition', recommendations: 'MCT oil for fat malabsorption. Elemental/semi-elemental formula. Vitamin and mineral supplementation. Monitor nutritional status.', recommendationsAr: 'زيت MCT لسوء امتصاص الدهون. تركيبة أولية/شبه أولية. مكملات الفيتامينات والمعادن. مراقبة الحالة الغذائية.', evidenceLevel: 'moderate', source: 'BSG 2022' },
  { condition: 'post_surgery', titleEn: 'Post-Surgery Nutrition', titleAr: 'التغذية بعد الجراحة', category: 'surgical_nutrition', recommendations: 'Early oral feeding within 24h if possible. Protein 1.5-2.0 g/kg/day. Vitamin C and zinc for wound healing.', recommendationsAr: 'تغذية فموية مبكرة خلال 24 ساعة إن أمكن. بروتين 1.5-2.0 غرام/كغم/يوم. فيتامين سي وزنك لالتئام الجروح.', evidenceLevel: 'high', source: 'ESPEN 2021' },
  { condition: 'burn_injury', titleEn: 'Burn Injury Nutrition', titleAr: 'التغذية للحروق', category: 'surgical_nutrition', recommendations: 'Energy 30-35 kcal/kg/day + 15-20 kcal/%TBSA burn. Protein 1.5-2.0 g/kg/day. Vitamin C 500mg, Zinc, Vitamin A supplementation.', recommendationsAr: 'طاقة 30-35 سعرة/كغم/يوم + 15-20 سعرة/نسبة الحرق. بروتين 1.5-2.0 غرام/كغم/يوم. فيتامين سي 500 ملغ وزنت وفيتامين أ.', evidenceLevel: 'high', source: 'ABA 2022' },
  { condition: 'copd', titleEn: 'COPD Nutrition', titleAr: 'التغذية لمرضى الانسداد الرئوي المزمن', category: 'pulmonary_nutrition', recommendations: 'Energy-dense, nutrient-rich diet. Protein 1.2-1.5 g/kg/day to preserve muscle mass. Omega-3 fatty acids. Small frequent meals.', recommendationsAr: 'نظام غذائي كثيف الطاقة غني بالمغذيات. بروتين 1.2-1.5 غرام/كغم/يوم. أحماض أوميغا-3 الدهنية. وجبات صغيرة متكررة.', evidenceLevel: 'moderate', source: 'ATS/ERS 2022' },
  { condition: 'geriatric_malnutrition', titleEn: 'Geriatric Malnutrition', titleAr: 'سوء التغذية لدى المسنين', category: 'geriatric_nutrition', recommendations: 'Screen with MNA. Protein 1.2-1.5 g/kg/day. Vitamin D 800-1000 IU/day. Calcium 1200mg/day. Oral nutritional supplements if intake inadequate.', recommendationsAr: 'فحص باستخدام MNA. بروتين 1.2-1.5 غرام/كغم/يوم. فيتامين د 800-1000 وحدة/يوم. كالسيوم 1200 ملغ/يوم. مكملات غذائية فموية.', evidenceLevel: 'high', source: 'ESPEN 2022' },
  { condition: 'eating_disorders', titleEn: 'Eating Disorder Nutrition', titleAr: 'التغذية لاضطرابات الأكل', category: 'mental_health_nutrition', recommendations: 'Multidisciplinary team approach. Medical stabilization first. Structured meal plans. Regular monitoring of refeeding syndrome.', recommendationsAr: 'نهج فريق متعدد التخصصات. تثبيت طبي أولاً. خطط وجبات منظمة. مراقبة متلازمة إعادة التغذية.', evidenceLevel: 'high', source: 'APA 2023' },
  { condition: 'crohns_disease', titleEn: "Crohn's Disease Nutrition", titleAr: 'التغذية لمرض كرون', category: 'gi_nutrition', recommendations: 'Exclusive EN for induction in children. Low fibre during flares. Calcium and vitamin D supplementation. Monitor B12, iron, folate.', recommendationsAr: 'تغذية معوية حصرية للحث في الأطفال. ألياف منخفضة أثناء النوبات. مكملات كالسيوم وفيتامين د. مراقبة B12 والحديد والفولات.', evidenceLevel: 'high', source: 'ECCO 2022' },
  { condition: 'ulcerative_colitis', titleEn: 'Ulcerative Colitis Nutrition', titleAr: 'التغذية لالتهاب القولون التقرحي', category: 'gi_nutrition', recommendations: 'No specific dietary restrictions. Iron supplementation for anaemia. Calcium and vitamin D for steroid-induced bone loss.', recommendationsAr: 'لا قيود غذائية محددة. مكملات الحديد لفقر الدم. كالسيوم وفيتامين د لفقدان العظام الناتج عن الستيرويد.', evidenceLevel: 'moderate', source: 'ECCO 2022' },
  { condition: 'pregnancy', titleEn: 'Pregnancy Nutrition', titleAr: 'التغذية أثناء الحمل', category: 'maternal_nutrition', recommendations: 'Extra 300-450 kcal/day in 2nd/3rd trimester. Folate 600mcg/day. Iron 27mg/day. Iodine 220mcg/day. Vitamin D 600 IU/day.', recommendationsAr: '300-450 سعرة إضافية/يوم في الثلث الثاني/الثالث. فولات 600 ميكروغرام/يوم. حديد 27 ملغ/يوم. يود 220 ميكروغرام/يوم.', evidenceLevel: 'high', source: 'WHO 2023' },
  { condition: 'lactation', titleEn: 'Lactation Nutrition', titleAr: 'التغذية أثناء الرضاعة', category: 'maternal_nutrition', recommendations: 'Extra 500 kcal/day. Fluids 3L/day. DHA 200-300mg/day. Iodine 290mcg/day. Protein 1.1g/kg/day.', recommendationsAr: '500 سعرة إضافية/يوم. سوائل 3 لتر/يوم. DHA 200-300 ملغ/يوم. يود 290 ميكروغرام/يوم. بروتين 1.1 غرام/كغم/يوم.', evidenceLevel: 'high', source: 'WHO 2023' },
  { condition: 'sarcopenia', titleEn: 'Sarcopenia Management', titleAr: 'إدارة ضمور العضلات', category: 'geriatric_nutrition', recommendations: 'Protein 1.2-1.5 g/kg/day. Leucine-rich proteins. Vitamin D 800 IU/day. Resistance exercise. Omega-3 supplementation.', recommendationsAr: 'بروتين 1.2-1.5 غرام/كغم/يوم. بروتينات غنية بالليوسين. فيتامين د 800 وحدة/يوم. تمارين مقاومة. مكملات أوميغا-3.', evidenceLevel: 'high', source: 'ESPEN 2022' },
  { condition: 'dysphagia', titleEn: 'Dysphagia Diet', titleAr: 'نظام غذائي لعسر البلع', category: 'gi_nutrition', recommendations: 'Texture-modified foods (IDDSI levels). Thickened liquids. High calorie density in small volumes. Posture and positioning during feeding.', recommendationsAr: 'أطعمة معدلة القوام (مستويات IDDSI). سوائل مثخنة. كثافة سعرية عالية بأحجام صغيرة. وضعية أثناء التغذية.', evidenceLevel: 'high', source: 'IDDSI 2023' },
  { condition: 'pku', titleEn: 'PKU Diet Management', titleAr: 'إدارة النظام الغذائي لبيلة الفينيل كيتون', category: 'inborn_errors', recommendations: 'Lifelong Phe-restricted diet. Phe-free medical formula. Regular blood Phe monitoring. Tyrosine supplementation. Close dietitian follow-up.', recommendationsAr: 'نظام غذائي مقيد بالفينيل ألانين مدى الحياة. تركيبة طبية خالية من Phe. مراقبة Phe في الدم. مكملات التيروسين. متابعة دقيقة.', evidenceLevel: 'high', source: 'ESPKU 2023' },
  { condition: 'post_bariatric', titleEn: 'Post-Bariatric Surgery Nutrition', titleAr: 'التغذية بعد جراحة السمنة', category: 'surgical_nutrition', recommendations: 'Liquid diet → pureed → soft → solid. Protein 60-80g/day. Multivitamin + B12, iron, calcium, vitamin D. Small portions, eat slowly.', recommendationsAr: 'سائل → مهروس → طري → صلب. بروتين 60-80 غرام/يوم. فيتامينات متعددة + B12 وحديد وكالسيوم وفيتامين د. أجزاء صغيرة.', evidenceLevel: 'high', source: 'ASMBS 2022' },
  { condition: 'parkinsons', titleEn: "Parkinson's Disease Nutrition", titleAr: 'التغذية لمرض باركنسون', category: 'neurological_nutrition', recommendations: 'High fibre for constipation. Protein redistribution for levodopa. Small frequent meals. Hydration management. Thickened liquids if needed.', recommendationsAr: 'ألياف عالية للإمساك. إعادة توزيع البروتين لليفودوبا. وجبات صغيرة متكررة. إدارة الترطيب. سوائل مثخنة عند الحاجة.', evidenceLevel: 'moderate', source: 'EFNS 2022' },
  { condition: 'hiv_aids', titleEn: 'HIV/AIDS Nutrition', titleAr: 'التغذية لفيروس نقص المناعة', category: 'infectious_disease_nutrition', recommendations: 'Energy 25-35 kcal/kg/day. Protein 1.2-1.5 g/kg/day. Micronutrient supplementation. Food safety education. Manage side effects of ARVs.', recommendationsAr: 'طاقة 25-35 سعرة/كغم/يوم. بروتين 1.2-1.5 غرام/كغم/يوم. مكملات المغذيات الدقيقة. تثقيف سلامة الغذاء.', evidenceLevel: 'high', source: 'WHO 2023' },
  { condition: 'tb', titleEn: 'TB Nutrition Management', titleAr: 'إدارة التغذية للسل', category: 'infectious_disease_nutrition', recommendations: 'Energy 30-40 kcal/kg/day. Protein 1.5-2.0 g/kg/day. Vitamin D supplementation. Monitor weight and nutritional status monthly.', recommendationsAr: 'طاقة 30-40 سعرة/كغم/يوم. بروتين 1.5-2.0 غرام/كغم/يوم. مكملات فيتامين د. مراقبة الوزن شهرياً.', evidenceLevel: 'high', source: 'WHO 2023' },
  { condition: 'metabolic_syndrome', titleEn: 'Metabolic Syndrome Diet', titleAr: 'النظام الغذائي لمتلازمة الأيض', category: 'weight_management', recommendations: 'Mediterranean dietary pattern. Weight loss 5-10%. Fiber 30-40g/day. Limit added sugars <10% calories. Physical activity 150 min/week.', recommendationsAr: 'نمط غذائي متوسطي. فقدان الوزن 5-10٪. ألياف 30-40 غرام/يوم. سكريات مضافة أقل من 10٪. نشاط بدني 150 دقيقة/أسبوع.', evidenceLevel: 'high', source: 'IDF 2023' },
  { condition: 'diverticulitis', titleEn: 'Diverticulitis Diet', titleAr: 'النظام الغذائي لالتهاب الرتوج', category: 'gi_nutrition', recommendations: 'Clear liquid diet during acute attack. Low fibre during recovery. Gradually increase fibre. Avoid seeds and nuts (controversial).', recommendationsAr: 'نظام غذائي سائل صافٍ أثناء النوبة الحادة. ألياف منخفضة أثناء التعافي. زيادة الألياف تدريجياً.', evidenceLevel: 'moderate', source: 'ACG 2022' },
  { condition: 'fatty_liver', titleEn: 'NAFLD/NASH Dietary Management', titleAr: 'الإدارة الغذائية لدهون الكبد', category: 'hepatic_nutrition', recommendations: 'Weight loss 7-10%. Mediterranean diet. Limit fructose. Vitamin E 800 IU/day in non-diabetic NASH. Coffee 2-3 cups/day.', recommendationsAr: 'فقدان الوزن 7-10٪. نظام متوسطي. الحد من الفركتوز. فيتامين هـ 800 وحدة/يوم. قهوة 2-3 أكواب/يوم.', evidenceLevel: 'high', source: 'AASLD 2023' },
  { condition: 'gout', titleEn: 'Gout Diet Management', titleAr: 'إدارة النظام الغذائي للنقرس', category: 'rheumatological_nutrition', recommendations: 'Limit purine-rich foods (organ meats, shellfish). Avoid alcohol especially beer. Low-fat dairy for urate excretion. Cherries may reduce flares.', recommendationsAr: 'الحد من الأطعمة الغنية بالبيورين. تجنب الكحول خاصة البيرة. ألبان قليلة الدسم. الكرز قد يقلل النوبات.', evidenceLevel: 'moderate', source: 'ACR 2023' },
  { condition: 'thyroid_disorders', titleEn: 'Thyroid Disease Nutrition', titleAr: 'التغذية لأمراض الغدة الدرقية', category: 'endocrine_nutrition', recommendations: 'Iodine intake appropriate for condition. Selenium 200mcg/day for Hashimoto\'s. Avoid excessive soy/iodine in hyperthyroidism.', recommendationsAr: 'تناول اليود المناسب للحالة. سيلينيوم 200 ميكروغرام/يوم لهاشيموتو. تجنب الصويا/اليود المفرط.', evidenceLevel: 'moderate', source: 'ATA 2022' },
  { condition: 'pancreatic_insufficiency', titleEn: 'Pancreatic Insufficiency Nutrition', titleAr: 'التغذية لقصور البنكرياس', category: 'gi_nutrition', recommendations: 'Pancreatic enzyme replacement with meals. MCT oil supplementation. Fat-soluble vitamin supplementation. Small frequent meals.', recommendationsAr: 'إنزيمات البنكرياس مع الوجبات. مكملات زيت MCT. مكملات فيتامينات ذائبة في الدهون. وجبات صغيرة متكررة.', evidenceLevel: 'high', source: 'ESPEN 2022' },
  { condition: 'gluten_allergy', titleEn: 'Celiac Disease Diet', titleAr: 'النظام الغذائي لمرض السيلياك', category: 'gi_nutrition', recommendations: 'Strict lifelong gluten-free diet. Avoid wheat, barley, rye. Check oats purity. Calcium and vitamin D supplementation. Annual dietitian review.', recommendationsAr: 'نظام غذائي خالٍ من الغلوتين مدى الحياة. تجنب القمح والشعير والجاودار. مكملات كالسيوم وفيتامين د. مراجعة سنوية.', evidenceLevel: 'high', source: 'ACG 2023' },
  { condition: 'food_allergy', titleEn: 'Food Allergy Management', titleAr: 'إدارة حساسية الطعام', category: 'allergy_nutrition', recommendations: 'Strict avoidance of allergen. Read food labels carefully. Emergency action plan with epinephrine. Alternative nutrient sources. Dietitian education.', recommendationsAr: 'تجنب صارم لمسبب الحساسية. قراءة ملصقات الطعام. خطة طوارئ مع إبينيفرين. مصادر غذائية بديلة. تثقيف.', evidenceLevel: 'high', source: 'AAAAI 2023' },
];

function generateGuidelines(): ClinicalGuidelineSeed[] {
  const guidelines: ClinicalGuidelineSeed[] = [];
  let idCounter = 0;

  for (let i = 0; i < 12; i++) {
    for (const c of CONDITIONS) {
      const year = 2020 + Math.floor(Math.random() * 6);
      const month = String(Math.floor(Math.random() * 12) + 1).padStart(2, '0');
      const day = String(Math.floor(Math.random() * 28) + 1).padStart(2, '0');
      guidelines.push({
        id: `guideline-${String(++idCounter).padStart(4, '0')}`,
        titleEn: `${c.titleEn} v${i + 1}`,
        titleAr: `${c.titleAr} الإصدار ${i + 1}`,
        category: c.category,
        condition: c.condition,
        recommendations: c.recommendations,
        evidenceLevel: c.evidenceLevel,
        source: c.source,
        publishedDate: `${year}-${month}-${day}`,
      });
    }
  }

  return guidelines;
}

export const clinicalGuidelines: ClinicalGuidelineSeed[] = generateGuidelines();
