import { ClinicalRecommendationSeed } from './seedData';

const RECOMMENDATION_TEMPLATES: Array<{
  titleEn: string;
  titleAr: string;
  condition: string;
  conditionAr: string;
  recommendation: string;
  recommendationAr: string;
  priority: 'low' | 'medium' | 'high';
  priorityAr: string;
}> = [
  { titleEn: 'Implement Carbohydrate Counting', titleAr: 'تطبيق حساب الكربوهيدرات', condition: 'diabetes_mellitus', conditionAr: 'داء السكري', recommendation: 'Start carbohydrate counting education for better glycaemic control. Aim for consistent carbohydrate intake at meals.', recommendationAr: 'بدء تعليم حساب الكربوهيدرات لتحسين التحكم في سكر الدم. استهدف تناول كربوهيدرات ثابت في الوجبات.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Reduce Sugar-Sweetened Beverages', titleAr: 'تقليل المشروبات المحلاة بالسكر', condition: 'diabetes_mellitus', conditionAr: 'داء السكري', recommendation: 'Eliminate all sugar-sweetened beverages. Replace with water, unsweetened tea or coffee.', recommendationAr: 'إزالة جميع المشروبات المحلاة بالسكر. استبدالها بالماء أو الشاي أو القهوة غير المحلاة.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Increase Dietary Fibre Intake', titleAr: 'زيادة تناول الألياف الغذائية', condition: 'diabetes_mellitus', conditionAr: 'داء السكري', recommendation: 'Increase fibre intake to 25-35g/day from whole grains, legumes, vegetables, and fruits.', recommendationAr: 'زيادة تناول الألياف إلى 25-35 غرام/يوم من الحبوب الكاملة والبقوليات والخضروات والفواكه.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'Review Insulin Regimen', titleAr: 'مراجعة نظام الأنسولين', condition: 'diabetes_type_1', conditionAr: 'السكري النوع الأول', recommendation: 'Adjust insulin doses based on glucose patterns and carbohydrate intake. Consider insulin-to-carbohydrate ratio.', recommendationAr: 'تعديل جرعات الأنسولين بناءً على أنماط الغلوكوز وتناول الكربوهيدرات.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Increase Glucose Monitoring', titleAr: 'زيادة مراقبة الغلوكوز', condition: 'diabetes_mellitus', conditionAr: 'داء السكري', recommendation: 'Increase blood glucose monitoring to 4-6 times daily for better glycaemic management.', recommendationAr: 'زيادة مراقبة سكر الدم إلى 4-6 مرات يومياً لتحسين إدارة سكر الدم.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'Implement Protein Restriction', titleAr: 'تطبيق تقييد البروتين', condition: 'chronic_kidney_disease', conditionAr: 'مرض الكلى المزمن', recommendation: 'Restrict protein intake to 0.6-0.8 g/kg/day for non-dialysis CKD stage 3-5 patients.', recommendationAr: 'تقييد تناول البروتين إلى 0.6-0.8 غرام/كغم/يوم لمرضى الكلى المزمن غير الخاضعين للغسيل في المرحلة 3-5.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Sodium Restriction <2g/day', titleAr: 'تقييد الصوديوم أقل من 2 غرام/يوم', condition: 'chronic_kidney_disease', conditionAr: 'مرض الكلى المزمن', recommendation: 'Limit sodium intake to less than 2g per day. Avoid processed foods, canned goods, and added salt.', recommendationAr: 'الحد من تناول الصوديوم إلى أقل من 2 غرام يومياً. تجنب الأطعمة المصنعة والمعلبة والملح المضاف.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Potassium Intake Individualisation', titleAr: 'تخصيص تناول البوتاسيوم', condition: 'chronic_kidney_disease', conditionAr: 'مرض الكلى المزمن', recommendation: 'Individualise potassium intake based on serum potassium levels. Avoid high-potassium foods if hyperkalemic.', recommendationAr: 'تخصيص تناول البوتاسيوم بناءً على مستوياته في الدم. تجنب الأطعمة عالية البوتاسيوم.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Phosphate Restriction', titleAr: 'تقييد الفوسفات', condition: 'chronic_kidney_disease', conditionAr: 'مرض الكلى المزمن', recommendation: 'Restrict phosphate intake to 800-1000mg/day. Avoid phosphate-containing additives and processed foods.', recommendationAr: 'تقييد تناول الفوسفات إلى 800-1000 ملغ/يوم. تجنب الإضافات المحتوية على الفوسفات.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Phosphate Binder Review', titleAr: 'مراجعة رابط الفوسفات', condition: 'haemodialysis', conditionAr: 'غسيل كلوي', recommendation: 'Review phosphate binder type and dosing with meals based on phosphate content of meals.', recommendationAr: 'مراجعة نوع وجرعة رابط الفوسفات مع الوجبات بناءً على محتوى الفوسفات.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'Weekly Lab Monitoring for HD', titleAr: 'مراقبة مختبر أسبوعية لغسيل الكلى', condition: 'haemodialysis', conditionAr: 'غسيل كلوي', recommendation: 'Monitor serum potassium, phosphate, calcium, and albumin weekly in haemodialysis patients.', recommendationAr: 'مراقبة البوتاسيوم والفوسفات والكالسيوم والألبومين أسبوعياً في مرضى غسيل الكلى.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Initiate Early Enteral Nutrition', titleAr: 'بدء التغذية المعوية المبكرة', condition: 'critical_illness', conditionAr: 'مرض حرج', recommendation: 'Start enteral nutrition within 24-48 hours of ICU admission if patient cannot eat orally.', recommendationAr: 'بدء التغذية المعوية خلال 24-48 ساعة من دخول العناية المركزة.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Optimise Protein Delivery ICU', titleAr: 'تحسين توصيل البروتين في العناية', condition: 'critical_illness', conditionAr: 'مرض حرج', recommendation: 'Target protein delivery of 1.2-2.0 g/kg/day. Use modular protein supplements if needed to meet goals.', recommendationAr: 'استهداف توصيل بروتين 1.2-2.0 غرام/كغم/يوم.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Implement Feeding Protocol', titleAr: 'تطبيق بروتوكول التغذية', condition: 'critical_illness', conditionAr: 'مرض حرج', recommendation: 'Use evidence-based feeding protocol to improve enteral nutrition delivery in the ICU.', recommendationAr: 'استخدام بروتوكول تغذية قائم على الأدلة لتحسين توصيل التغذية المعوية.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'Refeeding Syndrome Monitoring', titleAr: 'مراقبة متلازمة إعادة التغذية', condition: 'refeeding_syndrome', conditionAr: 'متلازمة إعادة التغذية', recommendation: 'Monitor potassium, phosphate, and magnesium daily for first 7 days in high-risk patients.', recommendationAr: 'مراقبة البوتاسيوم والفوسفات والمغنيسيوم يومياً لأول 7 أيام.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'High-Protein Diet for Cachexia', titleAr: 'نظام غذائي عالي البروتين للدنف', condition: 'cancer', conditionAr: 'سرطان', recommendation: 'Increase protein intake to 1.5-2.0 g/kg/day to counteract cachexia and maintain muscle mass.', recommendationAr: 'زيادة تناول البروتين إلى 1.5-2.0 غرام/كغم/يوم لمواجهة الدنف والحفاظ على كتلة العضلات.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Omega-3 Supplementation Cancer', titleAr: 'مكملات أوميغا-3 للسرطان', condition: 'cancer', conditionAr: 'سرطان', recommendation: 'Consider EPA supplementation (2g/day) to help stabilise weight and appetite in cancer cachexia.', recommendationAr: 'النظر في مكملات EPA (2 غرام/يوم) للمساعدة في تثبيت الوزن والشهية في دنف السرطان.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'Manage Chemotherapy Nausea', titleAr: 'إدارة الغثيان الكيميائي', condition: 'cancer', conditionAr: 'سرطان', recommendation: 'Small frequent meals. Avoid strong odours. Ginger supplementation. Anti-emetic before meals.', recommendationAr: 'وجبات صغيرة متكررة. تجنب الروائح القوية. مكملات الزنجبيل.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Oral Mucositis Diet', titleAr: 'نظام غذائي لالتهاب الفم', condition: 'cancer', conditionAr: 'سرطان', recommendation: 'Provide soft, bland, room-temperature foods. Avoid acidic, spicy, or rough-textured foods.', recommendationAr: 'توفير أطعمة طرية خفيفة في درجة حرارة الغرفة. تجنب الأطعمة الحمضية أو الحارة.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'RUTF Therapy for SAM', titleAr: 'علاج RUTF لسوء التغذية الحاد', condition: 'paediatric_malnutrition', conditionAr: 'سوء تغذية الأطفال', recommendation: 'Start ready-to-use therapeutic food (RUTF) for uncomplicated severe acute malnutrition.', recommendationAr: 'بدء الغذاء العلاجي الجاهز للاستخدام (RUTF) لسوء التغذية الحاد الوخيم غير المعقد.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Breastfeeding Support', titleAr: 'دعم الرضاعة الطبيعية', condition: 'paediatric_malnutrition', conditionAr: 'سوء تغذية الأطفال', recommendation: 'Promote exclusive breastfeeding for first 6 months. Continue up to 2 years with complementary foods.', recommendationAr: 'تعزيز الرضاعة الطبيعية الحصرية لأول 6 أشهر. الاستمرار حتى سنتين مع الأغذية التكميلية.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Weekly Growth Monitoring Paeds', titleAr: 'مراقبة النمو الأسبوعية للأطفال', condition: 'paediatric_malnutrition', conditionAr: 'سوء تغذية الأطفال', recommendation: 'Monitor weight, height, and MUAC weekly. Plot on WHO growth charts.', recommendationAr: 'مراقبة الوزن والطول ومحيط الذراع أسبوعياً. الرسم على مخططات النمو.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Vitamin A Supplementation', titleAr: 'مكملات فيتامين أ', condition: 'paediatric_malnutrition', conditionAr: 'سوء تغذية الأطفال', recommendation: 'Give vitamin A supplementation (200,000 IU) for children with measles or severe malnutrition.', recommendationAr: 'إعطاء مكملات فيتامين أ (200,000 وحدة دولية) للأطفال.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Late-Night Snack for Cirrhosis', titleAr: 'وجبة ليلية خفيفة لتليف الكبد', condition: 'liver_cirrhosis', conditionAr: 'تليف الكبد', recommendation: 'Provide a late-night snack of 200-400 kcal with protein to reduce muscle wasting in cirrhosis.', recommendationAr: 'توفير وجبة خفيفة ليلاً من 200-400 سعرة مع بروتين.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'Sodium Restriction for Ascites', titleAr: 'تقييد الصوديوم للاستسقاء', condition: 'liver_cirrhosis', conditionAr: 'تليف الكبد', recommendation: 'Limit sodium to <2g/day for management of ascites in cirrhotic patients.', recommendationAr: 'الحد من الصوديوم إلى أقل من 2 غرام/يوم لإدارة الاستسقاء.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Mediterranean Diet Dyslipidemia', titleAr: 'الحمية المتوسطية لخلل الدهون', condition: 'hyperlipidaemia', conditionAr: 'فرط شحميات الدم', recommendation: 'Adopt Mediterranean dietary pattern rich in olive oil, nuts, fish, legumes, and whole grains.', recommendationAr: 'اعتماد نمط غذائي متوسطي غني بزيت الزيتون والمكسرات والأسماك.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Reduce Saturated Fat', titleAr: 'تقليل الدهون المشبعة', condition: 'hyperlipidaemia', conditionAr: 'فرط شحميات الدم', recommendation: 'Limit saturated fat to <7% of total calories. Replace with mono and polyunsaturated fats.', recommendationAr: 'الحد من الدهون المشبعة إلى أقل من 7٪ من إجمالي السعرات.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Plant Stanols/Sterols', titleAr: 'ستانول/ستيرول نباتي', condition: 'hyperlipidaemia', conditionAr: 'فرط شحميات الدم', recommendation: 'Consider plant stanol/sterol supplementation (2g/day) for additional LDL reduction.', recommendationAr: 'النظر في مكملات الستانول/الستيرول النباتي.', priority: 'low', priorityAr: 'منخفضة' },
  { titleEn: 'Calorie Deficit Weight Loss', titleAr: 'عجز سعرات لفقدان الوزن', condition: 'obesity', conditionAr: 'سمنة', recommendation: 'Create 500-1000 kcal/day deficit for weight loss of 0.5-1 kg per week. Target 5-10% weight loss.', recommendationAr: 'إنشاء عجز 500-1000 سعرة/يوم لفقدان 0.5-1 كغم/أسبوع.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Increase Physical Activity', titleAr: 'زيادة النشاط البدني', condition: 'obesity', conditionAr: 'سمنة', recommendation: 'Recommend 150-300 minutes/week of moderate-intensity aerobic activity plus resistance training.', recommendationAr: 'التوصية بـ 150-300 دقيقة/أسبوع من النشاط الهوائي.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'Anti-Obesity Medications', titleAr: 'أدوية مضادة للسمنة', condition: 'obesity', conditionAr: 'سمنة', recommendation: 'For BMI >30 or >27 with comorbidity, consider anti-obesity medication as adjunct to lifestyle.', recommendationAr: 'لمؤشر كتلة الجسم >30 أو >27 مع مرض مصاحب.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'DASH Diet Hypertension', titleAr: 'حمية داش لارتفاع الضغط', condition: 'hypertension', conditionAr: 'ارتفاع ضغط الدم', recommendation: 'Adopt DASH eating plan. Reduce sodium to 1.5-2.3g/day. Increase potassium-rich foods.', recommendationAr: 'اعتماد خطة الأكل داش. تقليل الصوديوم إلى 1.5-2.3 غرام/يوم.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Heart Failure Fluid Management', titleAr: 'إدارة السوائل لفشل القلب', condition: 'heart_failure', conditionAr: 'فشل القلب', recommendation: 'Monitor daily weights. Fluid restriction 1.5-2L/day in fluid overload. Sodium <2g/day.', recommendationAr: 'مراقبة الوزن يومياً. تقييد السوائل 1.5-2 لتر/يوم.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'MNT for Gestational Diabetes', titleAr: 'العلاج الغذائي لسكري الحمل', condition: 'gestational_diabetes', conditionAr: 'سكري الحمل', recommendation: 'All GDM patients should receive MNT. Monitor BG 4 times daily. Minimum 175g CHO/day.', recommendationAr: 'جميع مريضات سكري الحمل يجب أن يحصلن على علاج غذائي.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'EN in Acute Pancreatitis', titleAr: 'تغذية معوية لالتهاب البنكرياس', condition: 'acute_pancreatitis', conditionAr: 'التهاب البنكرياس الحاد', recommendation: 'Start early EN within 24-48h in predicted severe pancreatitis. NG or NJ route acceptable.', recommendationAr: 'بدء التغذية المعوية المبكرة خلال 24-48 ساعة.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'ICU Glycaemic Control', titleAr: 'التحكم في السكر في العناية', condition: 'icu_hyperglycaemia', conditionAr: 'ارتفاع السكر في العناية', recommendation: 'Maintain blood glucose between 140-180 mg/dL. Avoid tight glycaemic control <110 mg/dL.', recommendationAr: 'الحفاظ على سكر الدم بين 140-180 ملغ/دل.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Post-Bariatric Protein Intake', titleAr: 'تناول البروتين بعد جراحة السمنة', condition: 'post_bariatric', conditionAr: 'بعد جراحة السمنة', recommendation: 'Consume 60-80g protein daily. Start with liquid protein supplements. Advance to solid proteins gradually.', recommendationAr: 'تناول 60-80 غرام بروتين يومياً.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Post-Bariatric Supplementation', titleAr: 'المكملات بعد جراحة السمنة', condition: 'post_bariatric', conditionAr: 'بعد جراحة السمنة', recommendation: 'Take daily multivitamin + B12, iron, calcium citrate, vitamin D. Monitor levels every 3-6 months.', recommendationAr: 'تناول فيتامينات متعددة + B12 وحديد وكالسيوم وفيتامين د يومياً.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Pressure Injury Protein', titleAr: 'بروتين لإصابات الضغط', condition: 'pressure_ulcer', conditionAr: 'قرحة الضغط', recommendation: 'Provide 1.5-2.0 g/kg/day protein for stage 3+ pressure injuries. Include vitamin C and zinc.', recommendationAr: 'توفير 1.5-2.0 غرام/كغم/يوم بروتين لإصابات الضغط المرحلة 3+.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Malnutrition Universal Screening', titleAr: 'فحص سوء التغذية الشامل', condition: 'malnutrition', conditionAr: 'سوء تغذية', recommendation: 'Screen all patients within 24h of admission using validated tool (MUST/MST/STAMP).', recommendationAr: 'فحص جميع المرضى خلال 24 ساعة من الدخول.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Dietitian Referral Protocol', titleAr: 'بروتوكول إحالة أخصائي التغذية', condition: 'malnutrition', conditionAr: 'سوء تغذية', recommendation: 'Refer high-risk patients to dietitian within 24h. Medium-risk within 72h. Low-risk weekly rescreen.', recommendationAr: 'إحالة المرضى عالي الخطورة لأخصائي التغذية خلال 24 ساعة.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Celiac Gluten-Free Diet', titleAr: 'نظام خالٍ من الغلوتين للسيلياك', condition: 'gluten_allergy', conditionAr: 'حساسية الغلوتين', recommendation: 'Strict lifelong gluten-free diet. Avoid all wheat, barley, rye. Check oats for purity.', recommendationAr: 'نظام غذائي خالٍ من الغلوتين مدى الحياة.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'NAFLD Weight Loss Target', titleAr: 'هدف فقدان الوزن لدهون الكبد', condition: 'fatty_liver', conditionAr: 'دهون الكبد', recommendation: 'Target 7-10% weight loss for NAFLD/NASH. Mediterranean diet. Limit fructose. Coffee 2-3 cups/day.', recommendationAr: 'استهداف فقدان 7-10٪ من الوزن لدهون الكبد.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'CKD Vitamin D Monitoring', titleAr: 'مراقبة فيتامين د لمرضى الكلى', condition: 'chronic_kidney_disease', conditionAr: 'مرض الكلى المزمن', recommendation: 'Monitor 25(OH)D levels annually. Supplement if <30 ng/mL. Use active vitamin D if GFR <30.', recommendationAr: 'مراقبة مستويات فيتامين د سنوياً.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'Anaemia Iron Monitoring', titleAr: 'مراقبة الحديد لفقر الدم', condition: 'anaemia', conditionAr: 'فقر الدم', recommendation: 'Check iron studies, B12, folate in all anaemic patients. Supplement based on deficiency type.', recommendationAr: 'فحص دراسات الحديد و B12 والفولات لجميع مرضى فقر الدم.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Peritoneal Dialysis Protein', titleAr: 'بروتين لغسيل الكلى البريتوني', condition: 'peritoneal_dialysis', conditionAr: 'غسيل كلوي بريتوني', recommendation: 'Protein 1.2-1.5 g/kg/day including dialysate losses. Energy 25-35 kcal/kg/day.', recommendationAr: 'بروتين 1.2-1.5 غرام/كغم/يوم.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Enteral Feed Advancement', titleAr: 'تقديم التغذية المعوية', condition: 'critical_illness', conditionAr: 'مرض حرج', recommendation: 'Start trophic feeding 10-20 mL/h. Advance by 20mL every 4-8h as tolerated to goal rate.', recommendationAr: 'بدء تغذية تغذوية 10-20 مل/ساعة. زيادة بمقدار 20 مل كل 4-8 ساعات.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'PN Line Care Protocol', titleAr: 'بروتوكول العناية بخط التغذية الوريدية', condition: 'pn_complication', conditionAr: 'مضاعفات التغذية الوريدية', recommendation: 'Use dedicated CVC lumen for PN. Change tubing every 24h. Use aseptic technique for all line access.', recommendationAr: 'استخدام تجويف مخصص للقسطرة الوريدية المركزية للتغذية الوريدية.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Trauma Patient Protein', titleAr: 'بروتين مريض الصدمة', condition: 'critical_illness', conditionAr: 'مرض حرج', recommendation: 'Provide 1.5-2.5 g/kg/day protein for major trauma. Early EN within 24h. Immunonutrition if available.', recommendationAr: 'توفير 1.5-2.5 غرام/كغم/يوم بروتين للصدمات الكبيرة.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Geriatric Hydration', titleAr: 'ترطيب المسنين', condition: 'geriatric_malnutrition', conditionAr: 'سوء تغذية المسنين', recommendation: 'Encourage 1.5-2L fluid daily unless contraindicated. Monitor for dehydration risk.', recommendationAr: 'تشجيع 1.5-2 لتر سوائل يومياً.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'Sarcopenia Exercise + Nutrition', titleAr: 'تمارين وتغذية لضمور العضلات', condition: 'sarcopenia', conditionAr: 'ضمور العضلات', recommendation: 'Combine resistance exercise 2-3x/week with protein 1.2-1.5 g/kg/day. Leucine-rich proteins preferred.', recommendationAr: 'الجمع بين تمارين المقاومة 2-3 مرات/أسبوع مع بروتين.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'PKU Phe Level Monitoring', titleAr: 'مراقبة مستوى Phe لبيلة الفينيل كيتون', condition: 'pku', conditionAr: 'بيلة الفينيل كيتون', recommendation: 'Monitor blood Phe weekly in infants, monthly in children/adults. Maintain Phe 120-360 µmol/L.', recommendationAr: 'مراقبة Phe في الدم أسبوعياً للرضع وشهرياً للأطفال.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: `Crohn's Disease EN Therapy`, titleAr: 'علاج التغذية المعوية لكرون', condition: 'crohns_disease', conditionAr: 'مرض كرون', recommendation: `Consider exclusive EN for 6-8 weeks for induction in paediatric Crohn's. Monitor growth and symptoms.`, recommendationAr: 'النظر في التغذية المعوية الحصرية لمدة 6-8 أسابيع.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Burn Injury Calorie Needs', titleAr: 'احتياجات السعرات للحروق', condition: 'burn_injury', conditionAr: 'حروق', recommendation: 'Calculate energy using Toronto formula. Protein 1.5-2.0 g/kg/day. Vitamin C 500mg + Zinc + Vitamin A.', recommendationAr: 'حساب الطاقة باستخدام معادلة تورونتو.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'COPD Energy-Dense Diet', titleAr: 'نظام كثيف الطاقة لمرضى الرئة', condition: 'copd', conditionAr: 'مرض الرئة المزمن', recommendation: 'Provide energy-dense, nutrient-rich diet in small frequent meals. Protein 1.2-1.5 g/kg/day.', recommendationAr: 'توفير نظام غذائي كثيف الطاقة غني بالمغذيات بوجبات صغيرة متكررة.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'ICU Micronutrient Supplementation', titleAr: 'مكملات المغذيات الدقيقة في العناية', condition: 'critical_illness', conditionAr: 'مرض حرج', recommendation: 'Provide standard multivitamin/trace element supplementation. Additional thiamine, vitamin C, vitamin D in selected patients.', recommendationAr: 'توفير مكملات فيتامينات وعناصر نزرة قياسية.', priority: 'medium', priorityAr: 'متوسطة' },
  { titleEn: 'Dysphagia IDDSI Levels', titleAr: 'مستويات IDDSI لعسر البلع', condition: 'dysphagia', conditionAr: 'عسر البلع', recommendation: 'Prescribe appropriate IDDSI level based on swallow assessment. Review and progress as tolerated.', recommendationAr: 'وصف مستوى IDDSI المناسب بناءً على تقييم البلع.', priority: 'high', priorityAr: 'عالية' },
  { titleEn: 'Post-Op Early Feeding', titleAr: 'تغذية مبكرة بعد الجراحة', condition: 'post_surgery', conditionAr: 'بعد الجراحة', recommendation: 'Start oral intake within 24h of surgery if safe. Advance diet as tolerated. Protein 1.5-2.0 g/kg/day.', recommendationAr: 'بدء التغذية الفموية خلال 24 ساعة من الجراحة إن أمكن.', priority: 'high', priorityAr: 'عالية' },
];

function generateRecommendations(): ClinicalRecommendationSeed[] {
  const recommendations: ClinicalRecommendationSeed[] = [];
  let idCounter = 0;

  for (let i = 0; i < 6; i++) {
    for (const t of RECOMMENDATION_TEMPLATES) {
      recommendations.push({
        id: `rec-${String(++idCounter).padStart(4, '0')}`,
        titleEn: t.titleEn,
        titleAr: t.titleAr,
        condition: t.condition,
        conditionAr: t.conditionAr,
        recommendation: t.recommendation,
        recommendationAr: t.recommendationAr,
        priority: t.priority,
        priorityAr: t.priorityAr,
      });
    }
  }

  return recommendations;
}

export const clinicalRecommendations: ClinicalRecommendationSeed[] = generateRecommendations();
