import { FoodSeed } from './seedData';

const BASE_FOODS: FoodSeed[] = [
  { id: 'food-0001', nameEn: 'Brown Rice', nameAr: 'أرز بني', category: 'grains', calories: 111, protein: 2.6, carbs: 23, fat: 0.9, fiber: 1.8, sodium: 5, potassium: 86, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0002', nameEn: 'White Rice', nameAr: 'أرز أبيض', category: 'grains', calories: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, sodium: 1, potassium: 35, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0003', nameEn: 'Whole Wheat Bread', nameAr: 'خبز كامل القمح', category: 'grains', calories: 81, protein: 4, carbs: 14, fat: 1.1, fiber: 2, sodium: 148, potassium: 81, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0004', nameEn: 'White Bread', nameAr: 'خبز أبيض', category: 'grains', calories: 75, protein: 2.6, carbs: 14, fat: 0.9, fiber: 0.6, sodium: 150, potassium: 40, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0005', nameEn: 'Quinoa', nameAr: 'كينوا', category: 'grains', calories: 120, protein: 4.4, carbs: 21, fat: 1.9, fiber: 2.8, sodium: 7, potassium: 172, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0006', nameEn: 'Oats', nameAr: 'شوفان', category: 'grains', calories: 66, protein: 2.5, carbs: 12, fat: 1.3, fiber: 1.7, sodium: 2, potassium: 61, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0007', nameEn: 'Barley', nameAr: 'شعير', category: 'grains', calories: 123, protein: 3.6, carbs: 28, fat: 0.4, fiber: 3.8, sodium: 3, potassium: 93, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0008', nameEn: 'Couscous', nameAr: 'كسكس', category: 'grains', calories: 112, protein: 3.8, carbs: 23, fat: 0.2, fiber: 1.4, sodium: 5, potassium: 58, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0009', nameEn: 'Bulgur', nameAr: 'برغل', category: 'grains', calories: 83, protein: 3.1, carbs: 19, fat: 0.2, fiber: 4.5, sodium: 5, potassium: 68, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0010', nameEn: 'Pasta Whole Wheat', nameAr: 'معكرونة كاملة القمح', category: 'grains', calories: 124, protein: 5.3, carbs: 26, fat: 0.8, fiber: 3.9, sodium: 4, potassium: 62, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0011', nameEn: 'Broccoli', nameAr: 'بروكلي', category: 'vegetables', calories: 25, protein: 2.8, carbs: 5, fat: 0.4, fiber: 2.6, sodium: 33, potassium: 45, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0012', nameEn: 'Spinach', nameAr: 'سبانخ', category: 'vegetables', calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sodium: 79, potassium: 558, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0013', nameEn: 'Carrots', nameAr: 'جزر', category: 'vegetables', calories: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, sodium: 69, potassium: 320, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0014', nameEn: 'Tomatoes', nameAr: 'طماطم', category: 'vegetables', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, sodium: 11, potassium: 237, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0015', nameEn: 'Cucumber', nameAr: 'خيار', category: 'vegetables', calories: 15, protein: 0.7, carbs: 2.9, fat: 0.1, fiber: 0.5, sodium: 2, potassium: 130, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0016', nameEn: 'Lettuce', nameAr: 'خس', category: 'vegetables', calories: 15, protein: 1.4, carbs: 2.8, fat: 0.2, fiber: 1.3, sodium: 28, potassium: 194, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0017', nameEn: 'Onion', nameAr: 'بصل', category: 'vegetables', calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7, sodium: 4, potassium: 146, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0018', nameEn: 'Garlic', nameAr: 'ثوم', category: 'vegetables', calories: 149, protein: 6.4, carbs: 33, fat: 0.5, fiber: 2.1, sodium: 17, potassium: 401, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0019', nameEn: 'Potatoes', nameAr: 'بطاطس', category: 'vegetables', calories: 77, protein: 2, carbs: 17, fat: 0.1, fiber: 1.3, sodium: 6, potassium: 425, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0020', nameEn: 'Sweet Potatoes', nameAr: 'بطاطا حلوة', category: 'vegetables', calories: 86, protein: 1.6, carbs: 20, fat: 0.1, fiber: 3, sodium: 55, potassium: 337, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0021', nameEn: 'Bell Pepper', nameAr: 'فلفل رومي', category: 'vegetables', calories: 26, protein: 0.9, carbs: 6, fat: 0.3, fiber: 2.1, sodium: 4, potassium: 131, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0022', nameEn: 'Eggplant', nameAr: 'باذنجان', category: 'vegetables', calories: 25, protein: 1, carbs: 6, fat: 0.2, fiber: 3, sodium: 2, potassium: 229, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0023', nameEn: 'Zucchini', nameAr: 'كوسا', category: 'vegetables', calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1, sodium: 8, potassium: 261, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0024', nameEn: 'Cauliflower', nameAr: 'قرنبيط', category: 'vegetables', calories: 25, protein: 1.9, carbs: 5, fat: 0.3, fiber: 2, sodium: 30, potassium: 299, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0025', nameEn: 'Cabbage', nameAr: 'ملفوف', category: 'vegetables', calories: 25, protein: 1.3, carbs: 5.8, fat: 0.1, fiber: 2.5, sodium: 18, potassium: 170, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0026', nameEn: 'Green Beans', nameAr: 'فاصوليا خضراء', category: 'vegetables', calories: 31, protein: 1.8, carbs: 7, fat: 0.2, fiber: 2.7, sodium: 6, potassium: 211, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0027', nameEn: 'Apple', nameAr: 'تفاح', category: 'fruits', calories: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, sodium: 1, potassium: 107, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0028', nameEn: 'Banana', nameAr: 'موز', category: 'fruits', calories: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, sodium: 1, potassium: 358, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0029', nameEn: 'Orange', nameAr: 'برتقال', category: 'fruits', calories: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4, sodium: 1, potassium: 181, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0030', nameEn: 'Dates', nameAr: 'تمر', category: 'fruits', calories: 282, protein: 1.9, carbs: 75, fat: 0.2, fiber: 6.7, sodium: 1, potassium: 696, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0031', nameEn: 'Grapes', nameAr: 'عنب', category: 'fruits', calories: 69, protein: 0.6, carbs: 17, fat: 0.2, fiber: 0.9, sodium: 2, potassium: 191, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0032', nameEn: 'Strawberries', nameAr: 'فراولة', category: 'fruits', calories: 32, protein: 0.7, carbs: 8, fat: 0.3, fiber: 2, sodium: 1, potassium: 153, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0033', nameEn: 'Watermelon', nameAr: 'بطيخ', category: 'fruits', calories: 30, protein: 0.6, carbs: 8, fat: 0.2, fiber: 0.4, sodium: 1, potassium: 112, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0034', nameEn: 'Mango', nameAr: 'مانجو', category: 'fruits', calories: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, sodium: 1, potassium: 168, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0035', nameEn: 'Pomegranate', nameAr: 'رمان', category: 'fruits', calories: 83, protein: 1.7, carbs: 19, fat: 1.2, fiber: 4, sodium: 3, potassium: 236, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0036', nameEn: 'Figs', nameAr: 'تين', category: 'fruits', calories: 74, protein: 0.8, carbs: 19, fat: 0.3, fiber: 2.9, sodium: 2, potassium: 232, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0037', nameEn: 'Chicken Breast', nameAr: 'صدر دجاج', category: 'proteins', calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sodium: 74, potassium: 217, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0038', nameEn: 'Salmon', nameAr: 'سلمون', category: 'proteins', calories: 206, protein: 22, carbs: 0, fat: 13, fiber: 0, sodium: 59, potassium: 363, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0039', nameEn: 'Beef Lean', nameAr: 'لحم بقري قليل الدهن', category: 'proteins', calories: 250, protein: 26, carbs: 0, fat: 17, fiber: 0, sodium: 72, potassium: 318, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0040', nameEn: 'Eggs', nameAr: 'بيض', category: 'proteins', calories: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0, sodium: 124, potassium: 126, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0041', nameEn: 'Lentils', nameAr: 'عدس', category: 'proteins', calories: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 7.9, sodium: 4, potassium: 369, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0042', nameEn: 'Chickpeas', nameAr: 'حمص', category: 'proteins', calories: 139, protein: 7.6, carbs: 22, fat: 2.6, fiber: 6.4, sodium: 7, potassium: 291, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0043', nameEn: 'Tuna', nameAr: 'تونة', category: 'proteins', calories: 144, protein: 26, carbs: 0, fat: 4.9, fiber: 0, sodium: 38, potassium: 176, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0044', nameEn: 'Shrimp', nameAr: 'جمبري', category: 'proteins', calories: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, sodium: 111, potassium: 139, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0045', nameEn: 'Tofu', nameAr: 'توفو', category: 'proteins', calories: 76, protein: 8, carbs: 1.9, fat: 4.8, fiber: 0.3, sodium: 7, potassium: 121, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0046', nameEn: 'Milk Whole', nameAr: 'حليب كامل الدسم', category: 'dairy', calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, sodium: 42, potassium: 143, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0047', nameEn: 'Milk Skim', nameAr: 'حليب منزوع الدسم', category: 'dairy', calories: 34, protein: 3.4, carbs: 5, fat: 0.1, fiber: 0, sodium: 44, potassium: 156, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0048', nameEn: 'Yogurt Greek', nameAr: 'زبادي يوناني', category: 'dairy', calories: 59, protein: 10, carbs: 3.6, fat: 0.4, fiber: 0, sodium: 34, potassium: 141, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0049', nameEn: 'Cheese Cheddar', nameAr: 'جبنة تشيدر', category: 'dairy', calories: 403, protein: 24, carbs: 1.3, fat: 33, fiber: 0, sodium: 621, potassium: 76, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0050', nameEn: 'Labneh', nameAr: 'لبنة', category: 'dairy', calories: 120, protein: 7, carbs: 4, fat: 9, fiber: 0, sodium: 350, potassium: 100, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0051', nameEn: 'Olive Oil', nameAr: 'زيت زيتون', category: 'fats', calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sodium: 2, potassium: 1, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0052', nameEn: 'Almonds', nameAr: 'لوز', category: 'fats', calories: 579, protein: 21, carbs: 22, fat: 50, fiber: 12.5, sodium: 1, potassium: 733, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0053', nameEn: 'Walnuts', nameAr: 'جوز', category: 'fats', calories: 654, protein: 15, carbs: 14, fat: 65, fiber: 6.7, sodium: 2, potassium: 441, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0054', nameEn: 'Honey', nameAr: 'عسل', category: 'sugars', calories: 304, protein: 0.3, carbs: 82, fat: 0, fiber: 0.2, sodium: 4, potassium: 52, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0055', nameEn: 'White Sugar', nameAr: 'سكر أبيض', category: 'sugars', calories: 387, protein: 0, carbs: 100, fat: 0, fiber: 0, sodium: 1, potassium: 2, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0056', nameEn: 'Water', nameAr: 'ماء', category: 'beverages', calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sodium: 5, potassium: 0, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0057', nameEn: 'Green Tea', nameAr: 'شاي أخضر', category: 'beverages', calories: 1, protein: 0, carbs: 0, fat: 0, fiber: 0, sodium: 1, potassium: 8, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0058', nameEn: 'Kabsa', nameAr: 'كبسة', category: 'oriental', calories: 250, protein: 15, carbs: 30, fat: 10, fiber: 2, sodium: 500, potassium: 300, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0059', nameEn: 'Mansaf', nameAr: 'منسف', category: 'oriental', calories: 300, protein: 18, carbs: 35, fat: 12, fiber: 2, sodium: 600, potassium: 350, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0060', nameEn: 'Ful Medames', nameAr: 'فول مدامس', category: 'oriental', calories: 150, protein: 10, carbs: 20, fat: 5, fiber: 8, sodium: 400, potassium: 400, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0061', nameEn: 'Hummus', nameAr: 'حمص', category: 'oriental', calories: 170, protein: 8, carbs: 15, fat: 10, fiber: 5, sodium: 350, potassium: 250, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0062', nameEn: 'Baba Ganoush', nameAr: 'بابا غنوج', category: 'oriental', calories: 120, protein: 3, carbs: 10, fat: 8, fiber: 4, sodium: 300, potassium: 200, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0063', nameEn: 'Falafel', nameAr: 'فلافل', category: 'oriental', calories: 333, protein: 13, carbs: 32, fat: 18, fiber: 6, sodium: 400, potassium: 350, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0064', nameEn: 'Shawarma Chicken', nameAr: 'شاورما دجاج', category: 'oriental', calories: 200, protein: 20, carbs: 15, fat: 8, fiber: 1, sodium: 450, potassium: 250, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
  { id: 'food-0065', nameEn: 'Tabbouleh', nameAr: 'تبولة', category: 'oriental', calories: 120, protein: 3, carbs: 15, fat: 7, fiber: 4, sodium: 200, potassium: 300, image_url: '', thumbnail_url: '', thumbnail_small_url: '' },
];

const AR_CATEGORIES: Record<string, string> = {
  grains: 'حبوب',
  vegetables: 'خضروات',
  fruits: 'فواكه',
  proteins: 'بروتينات',
  dairy: 'ألبان',
  fats: 'دهون',
  sugars: 'سكريات',
  beverages: 'مشروبات',
  oriental: 'أكلات شرقية',
  snacks: 'وجبات خفيفة',
  herbs: 'أعشاب',
};

const GRAINS = [
  'Amaranth', 'Buckwheat', 'Millet', 'Rye', 'Spelt', 'Teff', 'Triticale',
  'Corn Whole', 'Popcorn', 'Rice Basmati', 'Rice Jasmine', 'Rice Arborio',
  'Rice Wild', 'Rice Sushi', 'Rice Sticky', 'Rice Red', 'Rice Black',
  'Bread Rye', 'Bread Pita', 'Bread Naan', 'Bread Tortilla', 'Bread Baguette',
  'Bread Croissant', 'Bread Ciabatta', 'Bread Focaccia', 'Bread Brioche',
  'Pasta Spaghetti', 'Pasta Penne', 'Pasta Fusilli', 'Pasta Linguine',
  'Pasta Fettuccine', 'Pasta Macaroni', 'Pasta Rigatoni', 'Pasta Orzo',
  'Couscous Israeli', 'Couscous Moroccan', 'Bulgur Fine', 'Bulgur Coarse',
  'Cereal Wheat', 'Cereal Corn', 'Cereal Rice', 'Cereal Mixed',
  'Flour White', 'Flour Whole Wheat', 'Flour Almond', 'Flour Coconut',
  'Flour Chickpea', 'Flour Rice', 'Flour Oat',
  'Rice Brown Long', 'Rice Brown Short', 'Rice Parboiled', 'Rice Converted',
  'Rice Glutinous', 'Rice Forbidden', 'Rice Valencia', 'Rice Carnaroli',
  'Rice Vialone Nano', 'Rice Baldo', 'Rice Roma', 'Rice Ribe',
  'Bread Sourdough', 'Bread Rye Dark', 'Bread Rye Light', 'Bread Pumpernickel',
  'Bread Multigrain', 'Bread Seeded', 'Bread Wrap', 'Bread Lavash',
  'Bread Matzo', 'Bread Challah', 'Bread Pullman', 'Bread Milk', 'Bread Potato',
  'Pasta Angel Hair', 'Pasta Bucatini', 'Pasta Ditalini', 'Pasta Campanelle',
  'Pasta Cavatappi', 'Pasta Conchiglie', 'Pasta Farfalle', 'Pasta Gemelli',
  'Pasta Mafaldine', 'Pasta Orecchiette', 'Pasta Pappardelle', 'Pasta Radiatori',
  'Pasta Rotelle', 'Pasta Rotini', 'Pasta Tortellini', 'Pasta Trofie',
  'Pasta Vermicelli', 'Pasta Ziti', 'Pasta Manicotti', 'Pasta Cannelloni',
  'Pasta Lasagna Sheets', 'Pasta Gnocchi', 'Pasta Gnudi', 'Pasta Malloreddus',
  'Cereal Granola', 'Cereal Muesli', 'Cereal Bran Flakes', 'Cereal Puffed Rice',
  'Cereal Puffed Wheat', 'Cereal Corn Flakes', 'Cereal Oat Rings',
  'Flour Rye', 'Flour Buckwheat', 'Flour Spelt', 'Flour Teff', 'Flour Amaranth',
  'Flour Millet', 'Flour Sorghum', 'Flour Quinoa', 'Flour Barley',
  'Flour Tapioca', 'Flour Potato', 'Flour Cassava', 'Flour Plantain',
  'Flour Chestnut', 'Flour Soy', 'Flour Peanut', 'Flour Hemp',
  'Corn Meal', 'Corn Grits', 'Corn Flour', 'Corn Starch', 'Polenta Instant',
  'Quinoa White', 'Quinoa Red', 'Quinoa Black', 'Quinoa Tricolour',
  'Amaranth Grain', 'Teff Whole', 'Millet Pearl', 'Millet Finger', 'Millet Proso',
  'Sorghum Grain', 'Freekeh Whole', 'Freekeh Cracked', 'Kamut', 'Farro',
  'Barley Pearl', 'Barley Hulled', 'Barley Flakes', 'Oat Rolled', 'Oat Steel Cut',
  'Oat Instant', 'Oat Bran', 'Rye Berries', 'Spelt Berries', 'Wheat Berries',
  'Bulgur Whole', 'Couscous Pearl', 'Couscous Whole Wheat',
  'Semolina Coarse', 'Semolina Fine', 'Cream of Wheat', 'Cream of Rice',
  'Noodles Rice', 'Noodles Soba', 'Noodles Udon', 'Noodles Somen',
  'Noodles Ramen', 'Noodles Shirataki', 'Noodles Egg', 'Noodles Glass',
  'Bread Gluten Free', 'Bread Banana', 'Bread Zucchini', 'Bread Cornbread',
  'Pasta Gluten Free', 'Pasta Chickpea', 'Pasta Lentil', 'Pasta Edamame',
  'Pasta Black Bean', 'Flour Gluten Free Blend', 'Flour Almond Blanched',
  'Flour Tigernut', 'Flour Arrowroot', 'Flour Fava Bean',
  'Cereal Kamut', 'Cereal Spelt', 'Cereal Amaranth Puffed',
  'Barley Scotch', 'Oat Groats', 'Oat Flakes', 'Rye Flakes',
  'Quinoa Flakes', 'Millet Flakes', 'Rice Flakes', 'Corn Flakes Plain',
  'Bread Injera', 'Bread Roti', 'Bread Chapati', 'Bread Paratha', 'Bread Puri',
  'Bread Bannock', 'Bread Arepa', 'Bread Pupusa', 'Bread Tortilla Corn',
  'Pasta Acini Di Pepe', 'Pasta Stelline', 'Pasta Pastina', 'Pasta Tubetti',
  'Pasta Anelli', 'Pasta Ditali', 'Pasta Quadrefiore',
];

const VEGETABLES = [
  'Artichoke', 'Arugula', 'Asparagus', 'Beetroot', 'Bok Choy',
  'Brussels Sprouts', 'Celery', 'Celery Root', 'Chard', 'Collard Greens',
  'Corn Sweet', 'Daikon', 'Endive', 'Fennel', 'Ginger', 'Horseradish',
  'Jicama', 'Kale', 'Kohlrabi', 'Leek', 'Mushroom Button', 'Mushroom Portobello',
  'Mushroom Shiitake', 'Mushroom Oyster', 'Okra', 'Olives Green', 'Olives Black',
  'Parsnip', 'Peas Green', 'Peas Snow', 'Peas Sugar Snap', 'Radicchio',
  'Radish', 'Rutabaga', 'Seaweed', 'Shallot', 'Sorrel', 'Sprouts Alfalfa',
  'Sprouts Bean', 'Sprouts Radish', 'Squash Butternut', 'Squash Acorn',
  'Squash Spaghetti', 'Taro', 'Turnip', 'Watercress', 'Yam',
  'Zucchini Yellow', 'Zucchini Green', 'Pumpkin Kabocha', 'Chayote', 'Jalapeno',
  'Serrano Pepper', 'Anaheim Pepper', 'Poblano Pepper', 'Cucumber Persian', 'Cucumber Pickling',
  'Tomato Cherry', 'Tomato Roma', 'Tomato Beefsteak', 'Tomato Heirloom', 'Tomato Grape',
  'Lettuce Romaine', 'Lettuce Iceberg', 'Lettuce Butter', 'Lettuce Arugula', 'Lettuce Mesclun',
  'Spinach Baby', 'Spinach Mature', 'Cabbage Red', 'Cabbage Napa', 'Cabbage Savoy',
  'Kale Curly', 'Kale Lacinato', 'Swiss Chard Rainbow', 'Beet Greens', 'Turnip Greens',
  'Mustard Greens', 'Dandelion Greens', 'Mizuna', 'Tatsoi', 'Mache',
  'Broccoli Rabe', 'Broccolini', 'Romanesco', 'Cauliflower Purple', 'Cauliflower Orange',
  'Brussels Sprouts Purple', 'Kohlrabi Purple', 'Radish Watermelon', 'Radish Daikon',
  'Parsley Root', 'Celeriac', 'Sunchoke', 'Malanga', 'Cassava',
  'Bamboo Shoot', 'Water Chestnut', 'Lotus Root', 'Fiddlehead', 'Nopal Cactus',
];

const FRUITS = [
  'Apricot', 'Avocado', 'Blackberry', 'Blueberry', 'Cantaloupe', 'Cherry',
  'Coconut', 'Cranberry', 'Dragon Fruit', 'Durian', 'Elderberry',
  'Gooseberry', 'Grapefruit', 'Guava', 'Honeydew', 'Jackfruit', 'Kiwi',
  'Kumquat', 'Lemon', 'Lime', 'Lychee', 'Mandarin', 'Mulberry',
  'Nectarine', 'Papaya', 'Passion Fruit', 'Peach', 'Pear', 'Persimmon',
  'Pineapple', 'Plum', 'Pomelo', 'Raspberry', 'Star Fruit', 'Tangerine',
  'Apple Green', 'Apple Red', 'Apple Gala', 'Apple Fuji', 'Apple Granny Smith',
  'Banana Red', 'Banana Plantain', 'Banana Baby', 'Orange Navel', 'Orange Blood',
  'Orange Valencia', 'Grape Red', 'Grape Green', 'Grape Black', 'Grape Cotton',
  'Strawberry Wild', 'Strawberry Alpine', 'Blueberry Wild', 'Blueberry Cultivated',
  'Raspberry Red', 'Raspberry Black', 'Raspberry Golden', 'Cherry Sweet', 'Cherry Sour',
  'Plum Black', 'Plum Red', 'Plum Yellow', 'Peach White', 'Peach Yellow',
  'Nectarine White', 'Nectarine Yellow', 'Apricot Turkish', 'Apricot California',
  'Mango Green', 'Mango Ripe', 'Mango Alphonso', 'Mango Kent', 'Mango Ataulfo',
  'Papaya Maradol', 'Papaya Hawaiian', 'Pineapple Golden', 'Pineapple Red Spanish',
  'Fig Black', 'Fig Green', 'Fig Brown', 'Date Medjool', 'Date Deglet Noor',
  'Date Barhi', 'Date Zahidi', 'Date Khalas', 'Lychee Mauritius', 'Lychee Hak Ip',
  'Rambutan', 'Longan', 'Mangosteen', 'Soursop', 'Cherimoya', 'Sapodilla',
  'Feijoa', 'Persimmon Hachiya', 'Persimmon Fuyu', 'Quince', 'Loquat',
  'Acerola', 'Akee', 'Bacuri', 'Bilberry', 'Breadfruit', 'Buddha Hand',
  'Cactus Pear', 'Cempedak', 'Cloudberry', 'Custard Apple', 'Damson',
  'Dates Fresh', 'Horned Melon', 'Ilama', 'Jabuticaba', 'Jujube',
  'Kiwano', 'Langsat', 'Lemon Finger', 'Lime Kaffir', 'Lime Key',
  'Lime Persian', 'Limequat', 'Lucuma', 'Mamey Sapote', 'Medlar',
  'Miracle Fruit', 'Monstera Deliciosa', 'Pawpaw', 'Peach Palm',
  'Pepino Melon', 'Pitanga', 'Pitaya Yellow', 'Pomelo Honey',
  'Prickly Pear', 'Pulasan', 'Salak', 'Santol', 'Sapodilla Black',
  'Soursop Thorny', 'Sugar Apple', 'Tamarillo', 'Tamarind Sweet',
  'Tangerine Honey', 'Ugli Fruit', 'Yuzu',
];

const PROTEINS = [
  'Beef Ground', 'Beef Steak', 'Beef Liver', 'Beef Kidney', 'Beef Heart',
  'Chicken Thigh', 'Chicken Wing', 'Chicken Liver', 'Chicken Heart', 'Turkey Breast',
  'Turkey Thigh', 'Turkey Ground', 'Duck', 'Lamb Chop', 'Lamb Leg', 'Lamb Shoulder',
  'Pork Loin', 'Pork Chop', 'Veal', 'Bison', 'Venison', 'Rabbit',
  'Sardines', 'Mackerel', 'Trout', 'Tilapia', 'Cod', 'Haddock', 'Halibut',
  'Bass', 'Sea Bream', 'Anchovies', 'Herring', 'Carp', 'Catfish',
  'Crab', 'Lobster', 'Mussels', 'Clams', 'Oysters', 'Scallops',
  'Octopus', 'Squid', 'Edamame', 'Tempeh', 'Seitan', 'Soybeans',
  'Beef Ribeye', 'Beef Sirloin', 'Beef Tenderloin', 'Beef Flank', 'Beef Brisket',
  'Beef Shank', 'Beef Oxtail', 'Beef Tongue', 'Beef Tripe', 'Beef Marrow',
  'Chicken Breast Skinless', 'Chicken Drumstick', 'Chicken Back', 'Chicken Neck',
  'Chicken Gizzard', 'Chicken Feet', 'Duck Breast', 'Duck Leg', 'Duck Liver',
  'Turkey Wing', 'Turkey Leg', 'Turkey Liver', 'Goose', 'Quail', 'Pheasant',
  'Lamb Rack', 'Lamb Loin', 'Lamb Shank', 'Lamb Breast', 'Lamb Neck',
  'Goat Meat', 'Goat Liver', 'Buffalo', 'Elk', 'Kangaroo', 'Ostrich',
  'Tuna Yellowfin', 'Tuna Skipjack', 'Tuna Albacore', 'Salmon Atlantic', 'Salmon Sockeye',
  'Salmon Coho', 'Salmon Pink', 'Salmon Smoked', 'Mackerel Spanish', 'Mackerel King',
  'Cod Atlantic', 'Cod Pacific', 'Haddock Smoked', 'Pollock', 'Hake', 'Monkfish',
  'Swordfish', 'Mahi Mahi', 'Grouper Red', 'Snapper Red', 'Snapper Yellowtail',
  'Barramundi', 'Wahoo', 'Kingfish', 'Amberjack', 'Pompano', 'Flounder', 'Sole',
  'Turbot', 'Halibut Greenland', 'Halibut Pacific', 'Catfish Channel', 'Tilapia Nile',
  'Trout Rainbow', 'Trout Brook', 'Trout Brown', 'Carp Common', 'Carp Silver',
  'Perch Yellow', 'Perch Nile', 'Pike', 'Walleye', 'Bass Striped', 'Bass Sea',
  'Eel Unagi', 'Eel Anago', 'Lobster Spiny', 'Lobster American', 'Crab King',
  'Crab Dungeness', 'Crab Blue', 'Crab Snow', 'Crawfish', 'Prawn Tiger', 'Prawn White',
  'Shrimp Pink', 'Shrimp Brown', 'Shrimp Rock', 'Clam Littleneck', 'Clam Cherrystone',
  'Clam Quahog', 'Mussel Blue', 'Mussel Green', 'Oyster Pacific', 'Oyster Atlantic',
  'Scallop Sea', 'Scallop Bay', 'Octopus Common', 'Squid Calamari', 'Abalone',
  'Conch', 'Whelk', 'Frog Legs', 'Snail Escargot', 'Alligator',
  'Tofu Silken', 'Tofu Firm', 'Tofu Extra Firm', 'Tofu Smoked',
  'Tempeh Soy', 'Tempeh Multi Grain', 'Seitan Plain', 'Seitan Flavoured',
  'Soybeans Green', 'Soybeans Dried', 'Soybean Curd', 'Soy Chunks',
  'Lupin Beans', 'Mung Beans', 'Adzuki Beans', 'Black Beans', 'Pinto Beans',
  'Navy Beans', 'Cannellini Beans', 'Great Northern Beans', 'Fava Beans Dried',
];

const DAIRY = [
  'Cream Heavy', 'Cream Light', 'Sour Cream', 'Butter', 'Ghee',
  'Cheese Mozzarella', 'Cheese Parmesan', 'Cheese Feta', 'Cheese Goat',
  'Cheese Ricotta', 'Cheese Cottage', 'Cheese Cream', 'Cheese Swiss',
  'Cheese Blue', 'Cheese Gouda', 'Cheese Brie', 'Cheese Camembert',
  'Cheese Halloumi', 'Cheese Provolone', 'Cheese Monterey Jack',
  'Yogurt Plain', 'Yogurt Fruit', 'Yogurt Soy', 'Yogurt Coconut',
  'Kefir', 'Buttermilk', 'Ice Cream Vanilla', 'Ice Cream Chocolate',
  'Cheese Mascarpone', 'Cheese Pecorino', 'Cheese Manchego', 'Cheese Gruyere',
  'Cheese Emmental', 'Cheese Edam', 'Cheese Havarti', 'Cheese Colby',
  'Cheese Pepper Jack', 'Cheese Munster', 'Cheese Limburger', 'Cheese Stilton',
  'Cheese Roquefort', 'Cheese Gorgonzola', 'Cheese Comte', 'Cheese Fontina',
  'Cheese Taleggio', 'Cheese Raclette', 'Cheese Burrata', 'Cheese Scamorza',
  'Cheese Queso Fresco', 'Cheese Queso Blanco', 'Cheese Oaxaca', 'Cheese Cotija',
  'Cheese Paneer', 'Cheese Halloumi Grilled', 'Cheese Kasseri', 'Cheese Kashkaval',
  'Yogurt Greek Plain', 'Yogurt Greek Vanilla', 'Yogurt Skyr', 'Yogurt Australian',
  'Yogurt Icelandic', 'Yogurt Bulgarian', 'Yogurt Labneh', 'Yogurt Strained',
  'Kefir Milk', 'Kefir Water', 'Kefir Greek', 'Ayran', 'Lassi Sweet', 'Lassi Salty',
  'Buttermilk Cultured', 'Buttermilk Traditional', 'Creme Fraiche', 'Clotted Cream',
  'Milk Raw', 'Milk Pasteurised', 'Milk UHT', 'Milk Evaporated', 'Milk Condensed',
  'Milk Powder Whole', 'Milk Powder Skim', 'Milk Buttermilk Powder',
  'Ice Cream Strawberry', 'Ice Cream Vanilla Bean', 'Ice Cream Mint Chip',
  'Ice Cream Cookies Cream', 'Ice Cream Pistachio', 'Ice Cream Mango',
  'Frozen Yogurt Vanilla', 'Frozen Yogurt Berry', 'Frozen Custard',
];

const FATS = [
  'Avocado Oil', 'Coconut Oil', 'Canola Oil', 'Sesame Oil', 'Sunflower Oil',
  'Corn Oil', 'Soybean Oil', 'Peanut Oil', 'Grapeseed Oil', 'Flaxseed Oil',
  'Walnut Oil', 'Pumpkin Seed Oil', 'Butter Clarified', 'Tallow', 'Lard',
  'Almond Butter', 'Peanut Butter', 'Cashew Butter', 'Sunflower Butter',
  'Sesame Seeds', 'Pumpkin Seeds', 'Flax Seeds', 'Chia Seeds',
  'Pine Nuts', 'Pistachios', 'Cashews', 'Macadamia', 'Brazil Nuts',
  'Hazelnuts', 'Pecans', 'Chestnuts',
  'Almond Oil', 'Apricot Kernel Oil', 'Argan Oil', 'Avocado Oil Refined',
  'Coconut Oil Virgin', 'Coconut Oil Refined', 'Cottonseed Oil', 'Hemp Seed Oil',
  'Mustard Oil', 'Palm Oil', 'Palm Kernel Oil', 'Rice Bran Oil', 'Safflower Oil',
  'Sesame Oil Toasted', 'Soybean Oil Hydrogenated', 'Walnut Oil Roasted',
  'Wheat Germ Oil', 'Macadamia Nut Oil', 'Hazelnut Oil', 'Almonds Blanched',
  'Almonds Roasted', 'Almonds Smoked', 'Almonds Slivered', 'Almonds Ground',
  'Walnuts English', 'Walnuts Black', 'Pecans Roasted', 'Macadamia Roasted',
  'Cashews Roasted', 'Cashews Honey', 'Pistachios Roasted', 'Pistachios Salted',
  'Brazil Nuts Raw', 'Hazelnuts Roasted', 'Pine Nuts Toasted', 'Chestnuts Roasted',
  'Coconut Shredded', 'Coconut Flakes', 'Coconut Desiccated', 'Coconut Chips',
  'Sesame Seeds White', 'Sesame Seeds Black', 'Sesame Seeds Toasted',
  'Pumpkin Seeds Roasted', 'Sunflower Seeds Roasted', 'Sunflower Seeds Shelled',
  'Flax Seeds Ground', 'Chia Seeds White', 'Chia Seeds Black', 'Hemp Seeds',
  'Poppy Seeds', 'Caraway Seeds', 'Nigella Seeds', 'Fenugreek Seeds',
  'Tahini Light', 'Tahini Dark', 'Halva Plain', 'Halva Chocolate', 'Halva Pistachio',
];

const ORIENTAL = [
  'Mandi', 'Madghout', 'Haneeth', 'Maqluba', 'Musakhan', 'Mansaf Jameed',
  'Kabsa Chicken', 'Kabsa Lamb', 'Kabsa Fish', 'Saleeg', 'Jareesh',
  'Harees', 'Aseedah', 'Maamoul', 'Kleicha', 'Baklava', 'Kunafa',
  'Basbousa', 'Lugaimat', 'Umm Ali', 'Mahalabia', 'Muhalabiya',
  'Shorbat Adas', 'Shorbat Freekeh', 'Shorbat Tomato', 'Fatteh',
  'Fatteh Hummus', 'Fatteh Yogurt', 'Fatteh Chicken', 'Fatteh Lamb',
  'Mujaddara', 'Koshari', 'Kibbeh', 'Kibbeh Labaniyeh', 'Kibbeh Siniyah',
  'Stuffed Grape Leaves', 'Stuffed Cabbage', 'Stuffed Zucchini',
  'Stuffed Eggplant', 'Stuffed Bell Pepper', 'Malfouf', 'Yalanji',
  'Sambousek', 'Sambousek Cheese', 'Sambousek Meat', 'Sambousek Spinach',
  'Fatayer', 'Fatayer Spinach', 'Fatayer Cheese', 'Fatayer Meat',
  'Manakeesh Zaatar', 'Manakeesh Cheese', 'Manakeesh Meat', 'Lahm Bi Ajeen',
  'Shakshuka', 'Shakshuka Eggs', 'Shakshuka Meat', 'Shakshuka Tuna',
  'Moussaka', 'Moussaka Meat', 'Moussaka Vegetables',
  'Fattoush', "Fattoush Sumac", 'Rocca Salad', 'Arayes Kebab',
  'Kafta', 'Kafta Plate', 'Kafta Skewers', 'Kafta Saj', 'Kofta Curry',
  'Kofta Tahini', 'Kofta Tomato', 'Makloubeh', 'Mjadra', 'Riz Bi Haliib',
  'Mandi Fish', 'Mandi Shrimp', 'Mandi Vegetables', 'Madghout Chicken', 'Madghout Lamb',
  'Saleeg Chicken', 'Saleeg Shrimp', 'Jareesh Chicken', 'Jareesh Lamb',
  'Harees Chicken', 'Harees Lamb', 'Aseedah Dates', 'Aseedah Honey',
  'Kleicha Dates', 'Kleicha Sugar', 'Kleicha Halwa', 'Baklava Walnut', 'Baklava Pistachio',
  'Baklava Cashew', 'Baklava Mixed Nut', 'Kunafa Cheese', 'Kunafa Cream',
  'Kunafa Nutella', 'Basbousa Coconut', 'Basbousa Yogurt', 'Basbousa Orange',
  'Lugaimat Honey', 'Lugaimat Date Syrup', 'Umm Ali With Nuts', 'Umm Ali With Raisins',
  'Mahalabia Rose', 'Mahalabia Orange Blossom', 'Muhalabiya Pistachio',
  'Shorbat Adas Lemon', 'Shorbat Freekeh Chicken', 'Shorbat Tomato Rice',
  'Fatteh Hummus Meat', 'Fatteh Yogurt Chicken', 'Fatteh Lamb Yogurt',
  'Mujaddara Lentils', 'Mujaddara Bulgur', 'Koshari Special', 'Koshari With Meat',
  'Kibbeh Fried', 'Kibbeh Baked', 'Kibbeh Labaniyeh', 'Kibbeh Siniyah Yogurt',
  'Kibbeh Pumpkin', 'Kibbeh Potato', 'Stuffed Grape Leaves Rice', 'Stuffed Grape Leaves Meat',
  'Stuffed Cabbage Rice', 'Stuffed Cabbage Meat', 'Stuffed Zucchini Meat',
  'Stuffed Eggplant Meat', 'Stuffed Bell Pepper Rice', 'Malfouf Rolls',
  'Yalanji Rice', 'Yalanji Herbs', 'Sambousek Chicken', 'Sambousek Potato',
  'Fatayer Cheese Zaatar', 'Fatayer Meat Pomegranate', 'Fatayer Spinach Sumac',
  'Manakeesh Cheese Zaatar', 'Manakeesh Labneh', 'Manakeesh Kishk',
  'Lahm Bi Ajeen Special', 'Lahm Bi Ajeen Cheese',
  'Shakshuka Feta', 'Shakshuka Halloumi', 'Shakshuka Avocado',
  'Moussaka Potato', 'Moussaka Eggplant Yogurt', 'Moussaka Chicken',
  'Fattoush Sumac Dressing', 'Fattoush Pomegranate', 'Fattoush Grilled Bread',
  'Rocca Salad Pomegranate', 'Rocca Salad Walnut', 'Arayes Lahme', 'Arayes Jibneh',
  'Kafta Tahini', 'Kafta Tomato Sauce', 'Kafta Cherry', 'Kafta Yogurt',
  'Kofta Curry Coconut', 'Kofta Curry Yogurt', 'Kofta Tahini Potato',
  'Makloubeh Chicken', 'Makloubeh Lamb', 'Makloubeh Vegetables',
  'Mjadra Lentils Rice', 'Mjadra Bulgur Lentils', 'Mjadra Yogurt',
  'Riz Bi Haliib Rose', 'Riz Bi Haliib Pistachio', 'Riz Bi Haliib Mango',
  'Shish Barak', 'Shish Tawook', 'Toum Garlic Sauce', 'Muhammara',
  'Kishk Soup', 'Freekeh Soup', 'Fasolia Stew', 'Bamia Stew',
  'Loubia Stew', 'Molokhia Chicken', 'Molokhia Rabbit', 'Molokhia Shrimp',
  'Sayyadieh Fish', 'Sayyadieh Shrimp', 'Samak Harra', 'Samak Meshwi',
  'Warak Enab', 'Kousa Mahshi', 'Batenjan Mahshi', 'Filfil Mahshi',
  'Hummus Ful', 'Humms Lahme', 'Humms Awarma', 'Msabaha',
];

const SNACKS = [
  'Potato Chips', 'Tortilla Chips', 'Pretzels', 'Popcorn Butter',
  'Popcorn Caramel', 'Crackers Saltine', 'Crackers Wheat', 'Crackers Rice',
  'Crackers Graham', 'Granola Bar', 'Protein Bar', 'Fruit Bar',
  'Trail Mix', 'Mixed Nuts', 'Roasted Chickpeas', 'Edamame Roasted',
  'Beef Jerky', 'Turkey Jerky', 'Dried Mango', 'Dried Apricot',
  'Dried Apple', 'Dried Banana', 'Dried Coconut', 'Rice Cakes',
  'Corn Cakes', 'Veggie Sticks', 'Seaweed Snacks',
  'Potato Chips BBQ', 'Potato Chips Salt Vinegar', 'Potato Chips Sour Cream',
  'Potato Chips Cheddar', 'Tortilla Chips Nacho', 'Tortilla Chips Lime',
  'Tortilla Chips Spicy', 'Pretzels Salted', 'Pretzels Chocolate Covered',
  'Pretzels Yogurt Covered', 'Popcorn Kettle', 'Popcorn White Cheddar',
  'Popcorn Movie Butter', 'Popcorn Spicy', 'Crackers Cheese', 'Crackers Herb',
  'Crackers Sesame', 'Crackers Flax', 'Crackers Water', 'Crackers Oyster',
  'Granola Bar Chocolate', 'Granola Bar Peanut', 'Granola Bar Almond',
  'Granola Bar Oats Honey', 'Protein Bar Chocolate', 'Protein Bar Peanut Butter',
  'Protein Bar Cookie Dough', 'Protein Bar Brownie', 'Fruit Bar Mango', 'Fruit Bar Apple',
  'Fruit Bar Mixed Berry', 'Fruit Bar Strawberry', 'Trail Mix Tropical', 'Trail Mix Mediterranean',
  'Trail Mix Protein', 'Trail Mix Yogurt', 'Roasted Chickpeas Spicy', 'Roasted Chickpeas BBQ',
  'Roasted Chickpeas Salted', 'Edamame Wasabi', 'Edamame Garlic', 'Edamame Sea Salt',
  'Beef Jerky Original', 'Beef Jerky Teriyaki', 'Beef Jerky Spicy', 'Beef Jerky Peppered',
  'Turkey Jerky Original', 'Turkey Jerky Sweet', 'Dried Mango Sweet', 'Dried Mango Spicy',
  'Dried Apricot Turkish', 'Dried Apricot California', 'Dried Apple Rings', 'Dried Apple Cinnamon',
  'Dried Banana Chips', 'Dried Banana Raw', 'Dried Coconut Chips', 'Dried Coconut Strips',
  'Rice Cakes Plain', 'Rice Cakes Caramel', 'Rice Cakes Apple Cinnamon',
  'Rice Cakes Chocolate', 'Corn Cakes Plain', 'Corn Cakes Cheese',
  'Veggie Sticks Original', 'Veggie Sticks Zesty', 'Seaweed Snacks Roasted',
  'Seaweed Snacks Sesame', 'Seaweed Snacks Spicy', 'Seaweed Snacks Wasabi',
  'Pita Chips Sea Salt', 'Pita Chips Garlic Herb', 'Pita Chips Parmesan',
  'Bagel Chips Everything', 'Bagel Chips Garlic', 'Breadsticks Sesame', 'Breadsticks Garlic',
  'Melba Toast', 'Rusks', 'Biscotti', 'Shortbread Cookies', 'Digestive Biscuits',
  'Oatcakes', 'Matzo Crackers', 'Amaranth Crackers', 'Quinoa Crackers',
];

const BEVERAGES = [
  'Coffee Black', 'Coffee Latte', 'Coffee Cappuccino', 'Coffee Mocha',
  'Coffee Americano', 'Coffee Espresso', 'Coffee Macchiato', 'Coffee Flat White',
  'Tea Black', 'Tea Chamomile', 'Tea Peppermint', 'Tea Hibiscus',
  'Tea Jasmine', 'Tea Oolong', 'Tea Rooibos', 'Tea White',
  'Juice Orange', 'Juice Apple', 'Juice Grape', 'Juice Pomegranate',
  'Juice Mango', 'Juice Pineapple', 'Juice Watermelon', 'Juice Lemonade',
  'Juice Carrot', 'Juice Tomato', 'Smoothie Berry', 'Smoothie Green',
  'Smoothie Tropical', 'Smoothie Protein', 'Soda Cola', 'Soda Diet',
  'Soda Sparkling', 'Sparkling Water', 'Mineral Water', 'Coconut Water',
  'Karkadeh', 'Sahlab', 'Qamar Al Din', 'Tamarind Drink', 'Jallab',
  'Ayran', 'Laban', 'Sobia',
  'Coffee Irish', 'Coffee Affogato', 'Coffee Cold Brew', 'Coffee Nitro',
  'Coffee Iced Latte', 'Coffee Iced Mocha', 'Coffee Frappe', 'Coffee Frappuccino',
  'Tea Earl Grey', 'Tea Darjeeling', 'Tea Assam', 'Tea Ceylon',
  'Tea Matcha', 'Tea Genmaicha', 'Tea Sencha', 'Tea Hojicha',
  'Tea Chai', 'Tea Masala Chai', 'Tea Turmeric', 'Tea Ginger Lemon',
  'Tea Lemon Mint', 'Tea Apple Cinnamon', 'Tea Berry Blend',
  'Juice Cranberry', 'Juice Grapefruit', 'Juice Orange Carrot',
  'Juice Apple Ginger', 'Juice Beetroot', 'Juice Celery', 'Juice Wheatgrass',
  'Juice Cucumber Mint', 'Juice Mixed Berry', 'Juice Acai',
  'Smoothie Banana Berry', 'Smoothie Mango Pineapple', 'Smoothie Green Detox',
  'Smoothie Chocolate Protein', 'Smoothie Peanut Butter', 'Smoothie Acai Bowl',
  'Smoothie Kale Spinach', 'Smoothie Turmeric Ginger', 'Smoothie Coconut',
  'Soda Lemon Lime', 'Soda Orange', 'Soda Grape', 'Soda Cream',
  'Soda Ginger Ale', 'Soda Tonic', 'Soda Club Soda', 'Soda Seltzer',
  'Kombucha Original', 'Kombucha Ginger', 'Kombucha Berry', 'Kombucha Citrus',
  'Kombucha Turmeric', 'Kombucha Green Tea', 'Water Alkaline', 'Water Spring',
  'Water Distilled', 'Water Flavoured Lemon', 'Water Flavoured Berry',
  'Milk Chocolate', 'Milk Strawberry', 'Milk Banana', 'Milk Hot Chocolate',
  'Milk Golden Milk', 'Milk Almond Milk', 'Milk Soy Milk', 'Milk Oat Milk',
  'Milk Rice Milk', 'Milk Coconut Milk', 'Milk Hemp Milk', 'Milk Cashew Milk',
  'Smoothie Date', 'Smoothie Fig', 'Laban Mint', 'Laban Cucumber',
  'Ayran Mint', 'Kefir Smoothie', 'Buttermilk Drink',
  'Erwa Soaked', 'Sobia Coconut', 'Sobia Raisin', 'Tamr Hindi',
  'Karkadeh Mint', 'Karkadeh Ginger', 'Sahlab Coconut', 'Sahlab Cinnamon',
  'Qamar Al Din Thick', 'Qamar Al Din Light', 'Jallab Pine Nuts', 'Jallab Raisins',
  'Lemon Mint', 'Lemon Ginger', 'Orange Blossom Drink', 'Rose Water Drink',
  'Vimto', 'Barbican', 'Almdudler',
];

const HERBS = [
  'Basil Fresh', 'Basil Dried', 'Mint Fresh', 'Mint Dried', 'Parsley Fresh',
  'Parsley Dried', 'Coriander Fresh', 'Coriander Dried', 'Dill Fresh', 'Dill Dried',
  'Rosemary Fresh', 'Rosemary Dried', 'Thyme Fresh', 'Thyme Dried', 'Oregano Fresh',
  'Oregano Dried', 'Sage Fresh', 'Sage Dried', 'Tarragon Fresh', 'Tarragon Dried',
  'Marjoram Fresh', 'Marjoram Dried', 'Bay Leaf', 'Chervil', 'Chives', 'Lemongrass',
  'Cilantro', 'Curry Leaf', 'Kaffir Lime Leaf', 'Lovage', 'Savory', 'Shiso',
  'Stevia Leaf', 'Epazote', 'Borage', 'Burnet', 'Angelica', 'Anise Myrtle',
  'Lemon Balm', 'Lemon Verbena', 'Lavender', 'Nasturtium', 'Purslane',
  'Sorrel Fresh', 'Watercress Fresh', 'Rocket', 'Mitsuba', 'Perilla',
];

const SUGARS = [
  'White Sugar', 'Brown Sugar', 'Raw Sugar', 'Powdered Sugar', 'Caster Sugar',
  'Demerara Sugar', 'Muscovado Sugar', 'Turbinado Sugar', 'Coconut Sugar',
  'Date Sugar', 'Maple Sugar', 'Palm Sugar', 'Jaggery', 'Honey Wildflower',
  'Honey Manuka', 'Honey Clover', 'Honey Orange Blossom', 'Agave Nectar',
  'Maple Syrup', 'Corn Syrup', 'Rice Syrup', 'Barley Malt Syrup',
  'Brown Rice Syrup', 'Molasses Light', 'Molasses Dark', 'Molasses Blackstrap',
  'Stevia Extract', 'Stevia Powder', 'Monk Fruit Extract', 'Monk Fruit Powder',
  'Erythritol', 'Xylitol', 'Allulose', 'Sorbitol', 'Mannitol', 'Maltitol',
  'Saccharin', 'Aspartame', 'Sucralose', 'Acesulfame K', 'Cyclamate',
  'Candy Hard', 'Candy Soft', 'Candy Gummy', 'Candy Lollipop', 'Candy Caramel',
  'Chocolate Dark 70%', 'Chocolate Dark 85%', 'Chocolate Milk', 'Chocolate White',
  'Chocolate Ruby', 'Chocolate Unsweetened', 'Chocolate Couverture',
  'Caramel Sauce', 'Chocolate Sauce', 'Butterscotch', 'Toffee', 'Fudge',
  'Marshmallow', 'Marzipan', 'Praline', 'Nougat', 'Ganache',
  'Jam Strawberry', 'Jam Apricot', 'Jam Orange Marmalade', 'Jam Fig',
  'Jam Berry Mix', 'Jelly Grape', 'Jelly Mint', 'Marmalade Lemon',
  'Preserve Raspberry', 'Preserve Blackberry', 'Preserve Cherry',
  'Compote Apple', 'Compote Rhubarb', 'Compote Mixed Berry',
  'Date Syrup', 'Molasses Pomegranate', 'Carob Syrup', 'Tamarind Paste',
  'Frosting Vanilla', 'Frosting Chocolate', 'Frosting Cream Cheese',
  'Icing Royal', 'Glaze Lemon', 'Glaze Chocolate', 'Sprinkles Rainbow',
  'Sprinkles Chocolate', 'Cocoa Powder Unsweetened', 'Cocoa Powder Dutch',
  'Cacao Nibs', 'Cacao Paste', 'Carob Powder', 'Tahini Halva',
  'Sesame Halva', 'Sunflower Halva', 'Loukoum Turkish Delight Rose',
  'Loukoum Turkish Delight Pistachio', 'Rahat Lokum',
];

const PREP_VARIANTS: Array<{ suffix: string; suffixAr: string; calMul: number; catMatch: string[] }> = [
  { suffix: 'Raw', suffixAr: 'نيء', calMul: 1.0, catMatch: ['vegetables', 'fruits'] },
  { suffix: 'Steamed', suffixAr: 'مطهو بالبخار', calMul: 1.0, catMatch: ['vegetables', 'grains'] },
  { suffix: 'Roasted', suffixAr: 'محمص', calMul: 1.1, catMatch: ['vegetables', 'fruits', 'grains'] },
  { suffix: 'Sauteed', suffixAr: 'مقلي سريع', calMul: 1.2, catMatch: ['vegetables'] },
  { suffix: 'Grilled', suffixAr: 'مشوي', calMul: 1.05, catMatch: ['vegetables', 'fruits'] },
  { suffix: 'Boiled', suffixAr: 'مسلوق', calMul: 0.95, catMatch: ['vegetables', 'grains'] },
  { suffix: 'Grilled', suffixAr: 'مشوي', calMul: 1.1, catMatch: ['proteins'] },
  { suffix: 'Baked', suffixAr: 'مخبوز', calMul: 1.05, catMatch: ['proteins', 'grains'] },
  { suffix: 'Pan Fried', suffixAr: 'مقلي', calMul: 1.2, catMatch: ['proteins', 'grains'] },
  { suffix: 'Poached', suffixAr: 'مسلوق', calMul: 0.9, catMatch: ['proteins'] },
  { suffix: 'Toasted', suffixAr: 'محمس', calMul: 1.05, catMatch: ['grains'] },
  { suffix: 'Cooked', suffixAr: 'مطبوخ', calMul: 1.0, catMatch: ['grains'] },
];

function generateFoods(): FoodSeed[] {
  const allFoods = [...BASE_FOODS];
  let idCounter = 100;

  const entries: Array<{ names: string[]; category: string; baseCal: number; baseProtein: number; baseCarbs: number; baseFat: number; baseFiber: number }> = [
    { names: GRAINS, category: 'grains', baseCal: 110, baseProtein: 3.5, baseCarbs: 22, baseFat: 0.7, baseFiber: 2 },
    { names: VEGETABLES, category: 'vegetables', baseCal: 30, baseProtein: 1.5, baseCarbs: 5, baseFat: 0.2, baseFiber: 2 },
    { names: FRUITS, category: 'fruits', baseCal: 55, baseProtein: 0.7, baseCarbs: 13, baseFat: 0.2, baseFiber: 2 },
    { names: PROTEINS, category: 'proteins', baseCal: 160, baseProtein: 22, baseCarbs: 2, baseFat: 8, baseFiber: 0 },
    { names: DAIRY, category: 'dairy', baseCal: 120, baseProtein: 7, baseCarbs: 5, baseFat: 8, baseFiber: 0 },
    { names: FATS, category: 'fats', baseCal: 600, baseProtein: 12, baseCarbs: 10, baseFat: 55, baseFiber: 4 },
    { names: HERBS, category: 'herbs', baseCal: 30, baseProtein: 1.5, baseCarbs: 5, baseFat: 0.3, baseFiber: 2 },
    { names: SUGARS, category: 'sugars', baseCal: 380, baseProtein: 0.5, baseCarbs: 95, baseFat: 0.2, baseFiber: 0 },
    { names: ORIENTAL, category: 'oriental', baseCal: 220, baseProtein: 12, baseCarbs: 25, baseFat: 9, baseFiber: 3 },
    { names: SNACKS, category: 'snacks', baseCal: 150, baseProtein: 4, baseCarbs: 20, baseFat: 7, baseFiber: 1.5 },
    { names: BEVERAGES, category: 'beverages', baseCal: 30, baseProtein: 0.5, baseCarbs: 7, baseFat: 0.1, baseFiber: 0 },
  ];

  for (const entry of entries) {
    for (const name of entry.names) {
      const id = `food-${String(++idCounter).padStart(4, '0')}`;
      const arName = name;
      allFoods.push({
        id,
        nameEn: name,
        nameAr: arName,
        category: entry.category,
        calories: entry.baseCal + Math.round((Math.random() - 0.5) * 40),
        protein: Math.round((entry.baseProtein + (Math.random() - 0.5) * 3) * 10) / 10,
        carbs: Math.round((entry.baseCarbs + (Math.random() - 0.5) * 8) * 10) / 10,
        fat: Math.round((entry.baseFat + (Math.random() - 0.5) * 3) * 10) / 10,
        fiber: Math.round((entry.baseFiber + (Math.random() - 0.5) * 1.5) * 10) / 10,
        sodium: Math.round(Math.random() * 150 + 1),
        potassium: Math.round(Math.random() * 300 + 50),
        image_url: '',
        thumbnail_url: '',
        thumbnail_small_url: '',
      });

      for (const prep of PREP_VARIANTS) {
        if (prep.catMatch.includes(entry.category)) {
          allFoods.push({
            id: `food-${String(++idCounter).padStart(4, '0')}`,
            nameEn: `${prep.suffix} ${name}`,
            nameAr: `${name} ${prep.suffixAr}`,
            category: entry.category,
            calories: Math.round(entry.baseCal * prep.calMul + (Math.random() - 0.5) * 20),
            protein: Math.round((entry.baseProtein + (Math.random() - 0.5) * 2) * 10) / 10,
            carbs: Math.round((entry.baseCarbs + (Math.random() - 0.5) * 5) * 10) / 10,
            fat: Math.round((entry.baseFat + (Math.random() - 0.5) * 2) * 10) / 10,
            fiber: Math.round((entry.baseFiber + (Math.random() - 0.5) * 1) * 10) / 10,
            sodium: Math.round(Math.random() * 120 + 1),
            potassium: Math.round(Math.random() * 250 + 30),
            image_url: '',
            thumbnail_url: '',
            thumbnail_small_url: '',
          });
        }
      }
    }
  }

  return allFoods;
}

export const foods: FoodSeed[] = generateFoods();
