export type LabTestCategory =
  | 'electrolytes'
  | 'kidneyFunction'
  | 'liverFunction'
  | 'bloodCount'
  | 'nutritionMetabolic'
  | 'thyroid'
  | 'coagulation'
  | 'other';

export interface LabTestParameter {
  code: string;
  name: string;
  nameAr: string;
  category: LabTestCategory;
  unit: string;
  referenceRangeLow: number | null;
  referenceRangeHigh: number | null;
  isCritical: boolean;
  criticalLow: number | null;
  criticalHigh: number | null;
}

export const LAB_TEST_PARAMETERS: Record<string, LabTestParameter> = {
  // ─── Electrolytes ───────────────────────────────────────────
  NA: {
    code: 'NA',
    name: 'Sodium',
    nameAr: 'الصوديوم',
    category: 'electrolytes',
    unit: 'mEq/L',
    referenceRangeLow: 135,
    referenceRangeHigh: 145,
    isCritical: true,
    criticalLow: 120,
    criticalHigh: 160,
  },
  K: {
    code: 'K',
    name: 'Potassium',
    nameAr: 'البوتاسيوم',
    category: 'electrolytes',
    unit: 'mEq/L',
    referenceRangeLow: 3.5,
    referenceRangeHigh: 5.0,
    isCritical: true,
    criticalLow: 2.5,
    criticalHigh: 6.5,
  },
  CL: {
    code: 'CL',
    name: 'Chloride',
    nameAr: 'الكلوريد',
    category: 'electrolytes',
    unit: 'mEq/L',
    referenceRangeLow: 96,
    referenceRangeHigh: 106,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  CA: {
    code: 'CA',
    name: 'Calcium',
    nameAr: 'الكالسيوم',
    category: 'electrolytes',
    unit: 'mg/dL',
    referenceRangeLow: 8.5,
    referenceRangeHigh: 10.5,
    isCritical: true,
    criticalLow: 6.0,
    criticalHigh: 13.0,
  },
  MG: {
    code: 'MG',
    name: 'Magnesium',
    nameAr: 'المغنيسيوم',
    category: 'electrolytes',
    unit: 'mg/dL',
    referenceRangeLow: 1.7,
    referenceRangeHigh: 2.2,
    isCritical: true,
    criticalLow: 1.0,
    criticalHigh: 3.0,
  },
  PHOS: {
    code: 'PHOS',
    name: 'Phosphorus',
    nameAr: 'الفسفور',
    category: 'electrolytes',
    unit: 'mg/dL',
    referenceRangeLow: 2.5,
    referenceRangeHigh: 4.5,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },

  // ─── Kidney Function ────────────────────────────────────────
  CREAT: {
    code: 'CREAT',
    name: 'Creatinine',
    nameAr: 'الكرياتينين',
    category: 'kidneyFunction',
    unit: 'mg/dL',
    referenceRangeLow: 0.6,
    referenceRangeHigh: 1.2,
    isCritical: true,
    criticalLow: null,
    criticalHigh: 4.0,
  },
  BUN: {
    code: 'BUN',
    name: 'Blood Urea Nitrogen',
    nameAr: 'نيتروجين يوريا الدم',
    category: 'kidneyFunction',
    unit: 'mg/dL',
    referenceRangeLow: 7,
    referenceRangeHigh: 20,
    isCritical: true,
    criticalLow: null,
    criticalHigh: 100,
  },
  EGFR: {
    code: 'EGFR',
    name: 'eGFR',
    nameAr: 'معدل الترشيح الكبيبي',
    category: 'kidneyFunction',
    unit: 'mL/min/1.73m²',
    referenceRangeLow: 60,
    referenceRangeHigh: null,
    isCritical: true,
    criticalLow: 15,
    criticalHigh: null,
  },

  // ─── Liver Function ─────────────────────────────────────────
  ALT: {
    code: 'ALT',
    name: 'ALT (SGPT)',
    nameAr: 'ALT (SGPT)',
    category: 'liverFunction',
    unit: 'U/L',
    referenceRangeLow: 7,
    referenceRangeHigh: 56,
    isCritical: true,
    criticalLow: null,
    criticalHigh: 1000,
  },
  AST: {
    code: 'AST',
    name: 'AST (SGOT)',
    nameAr: 'AST (SGOT)',
    category: 'liverFunction',
    unit: 'U/L',
    referenceRangeLow: 10,
    referenceRangeHigh: 40,
    isCritical: true,
    criticalLow: null,
    criticalHigh: 1000,
  },
  ALP: {
    code: 'ALP',
    name: 'Alkaline Phosphatase',
    nameAr: 'الفوسفاتاز القلوي',
    category: 'liverFunction',
    unit: 'U/L',
    referenceRangeLow: 44,
    referenceRangeHigh: 147,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  TBIL: {
    code: 'TBIL',
    name: 'Total Bilirubin',
    nameAr: 'البيليروبين الكلي',
    category: 'liverFunction',
    unit: 'mg/dL',
    referenceRangeLow: 0.1,
    referenceRangeHigh: 1.2,
    isCritical: true,
    criticalLow: null,
    criticalHigh: 15,
  },
  DBIL: {
    code: 'DBIL',
    name: 'Direct Bilirubin',
    nameAr: 'البيليروبين المباشر',
    category: 'liverFunction',
    unit: 'mg/dL',
    referenceRangeLow: 0,
    referenceRangeHigh: 0.3,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  TP: {
    code: 'TP',
    name: 'Total Protein',
    nameAr: 'البروتين الكلي',
    category: 'liverFunction',
    unit: 'g/dL',
    referenceRangeLow: 6.0,
    referenceRangeHigh: 8.3,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  ALB: {
    code: 'ALB',
    name: 'Albumin',
    nameAr: 'الألبومين',
    category: 'liverFunction',
    unit: 'g/dL',
    referenceRangeLow: 3.4,
    referenceRangeHigh: 5.4,
    isCritical: true,
    criticalLow: 1.5,
    criticalHigh: null,
  },

  // ─── Blood Count ────────────────────────────────────────────
  HCT: {
    code: 'HCT',
    name: 'Hematocrit',
    nameAr: 'الهيماتوكريت',
    category: 'bloodCount',
    unit: '%',
    referenceRangeLow: 36,
    referenceRangeHigh: 48,
    isCritical: true,
    criticalLow: 15,
    criticalHigh: 60,
  },
  MCV: {
    code: 'MCV',
    name: 'Mean Corpuscular Volume',
    nameAr: 'متوسط حجم الكرية',
    category: 'bloodCount',
    unit: 'fL',
    referenceRangeLow: 80,
    referenceRangeHigh: 100,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  MCH: {
    code: 'MCH',
    name: 'Mean Corpuscular Hemoglobin',
    nameAr: 'متوسط هيموجلوبين الكرية',
    category: 'bloodCount',
    unit: 'pg',
    referenceRangeLow: 27,
    referenceRangeHigh: 34,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  PLT: {
    code: 'PLT',
    name: 'Platelet Count',
    nameAr: 'عدد الصفائح الدموية',
    category: 'bloodCount',
    unit: '×10³/µL',
    referenceRangeLow: 150,
    referenceRangeHigh: 450,
    isCritical: true,
    criticalLow: 20,
    criticalHigh: 1000,
  },
  WBC: {
    code: 'WBC',
    name: 'White Blood Cell Count',
    nameAr: 'عدد خلايا الدم البيضاء',
    category: 'bloodCount',
    unit: '×10³/µL',
    referenceRangeLow: 4.0,
    referenceRangeHigh: 11.0,
    isCritical: true,
    criticalLow: 0.5,
    criticalHigh: 30,
  },

  // ─── Nutrition / Metabolic ──────────────────────────────────
  CHOL: {
    code: 'CHOL',
    name: 'Total Cholesterol',
    nameAr: 'الكوليسترول الكلي',
    category: 'nutritionMetabolic',
    unit: 'mg/dL',
    referenceRangeLow: 125,
    referenceRangeHigh: 200,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  LDL: {
    code: 'LDL',
    name: 'LDL Cholesterol',
    nameAr: 'LDL الكوليسترول',
    category: 'nutritionMetabolic',
    unit: 'mg/dL',
    referenceRangeLow: 0,
    referenceRangeHigh: 100,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  HDL: {
    code: 'HDL',
    name: 'HDL Cholesterol',
    nameAr: 'HDL الكوليسترول',
    category: 'nutritionMetabolic',
    unit: 'mg/dL',
    referenceRangeLow: 40,
    referenceRangeHigh: 60,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  TG: {
    code: 'TG',
    name: 'Triglycerides',
    nameAr: 'الدهون الثلاثية',
    category: 'nutritionMetabolic',
    unit: 'mg/dL',
    referenceRangeLow: 0,
    referenceRangeHigh: 150,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  GLU: {
    code: 'GLU',
    name: 'Glucose (Fasting)',
    nameAr: 'الجلوكوز (صائم)',
    category: 'nutritionMetabolic',
    unit: 'mg/dL',
    referenceRangeLow: 70,
    referenceRangeHigh: 100,
    isCritical: true,
    criticalLow: 40,
    criticalHigh: 500,
  },
  HBA1C: {
    code: 'HBA1C',
    name: 'HbA1c',
    nameAr: 'HbA1c',
    category: 'nutritionMetabolic',
    unit: '%',
    referenceRangeLow: 4.0,
    referenceRangeHigh: 5.7,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  B12: {
    code: 'B12',
    name: 'Vitamin B12',
    nameAr: 'فيتامين B12',
    category: 'nutritionMetabolic',
    unit: 'pg/mL',
    referenceRangeLow: 200,
    referenceRangeHigh: 900,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  VITD: {
    code: 'VITD',
    name: 'Vitamin D (25-OH)',
    nameAr: 'فيتامين D',
    category: 'nutritionMetabolic',
    unit: 'ng/mL',
    referenceRangeLow: 30,
    referenceRangeHigh: 80,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  IRON: {
    code: 'IRON',
    name: 'Iron',
    nameAr: 'الحديد',
    category: 'nutritionMetabolic',
    unit: 'µg/dL',
    referenceRangeLow: 60,
    referenceRangeHigh: 170,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  TIBC: {
    code: 'TIBC',
    name: 'Total Iron Binding Capacity',
    nameAr: 'إجمالي قدرة ربط الحديد',
    category: 'nutritionMetabolic',
    unit: 'µg/dL',
    referenceRangeLow: 250,
    referenceRangeHigh: 450,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  FERRITIN: {
    code: 'FERRITIN',
    name: 'Ferritin',
    nameAr: 'الفيريتين',
    category: 'nutritionMetabolic',
    unit: 'ng/mL',
    referenceRangeLow: 20,
    referenceRangeHigh: 300,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },

  // ─── Thyroid ────────────────────────────────────────────────
  TSH: {
    code: 'TSH',
    name: 'TSH',
    nameAr: 'TSH',
    category: 'thyroid',
    unit: 'µIU/mL',
    referenceRangeLow: 0.4,
    referenceRangeHigh: 4.0,
    isCritical: true,
    criticalLow: 0.01,
    criticalHigh: 100,
  },
  T3: {
    code: 'T3',
    name: 'T3 Total',
    nameAr: 'T3 الكلي',
    category: 'thyroid',
    unit: 'ng/dL',
    referenceRangeLow: 80,
    referenceRangeHigh: 200,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
  T4FREE: {
    code: 'T4FREE',
    name: 'T4 Free',
    nameAr: 'T4 الحر',
    category: 'thyroid',
    unit: 'ng/dL',
    referenceRangeLow: 0.8,
    referenceRangeHigh: 1.8,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },

  // ─── Coagulation ────────────────────────────────────────────
  PT: {
    code: 'PT',
    name: 'Prothrombin Time',
    nameAr: 'زمن البروثرومبين',
    category: 'coagulation',
    unit: 'seconds',
    referenceRangeLow: 11,
    referenceRangeHigh: 13.5,
    isCritical: true,
    criticalLow: null,
    criticalHigh: 30,
  },
  INR: {
    code: 'INR',
    name: 'INR',
    nameAr: 'INR',
    category: 'coagulation',
    unit: 'ratio',
    referenceRangeLow: 0.8,
    referenceRangeHigh: 1.2,
    isCritical: true,
    criticalLow: null,
    criticalHigh: 5.0,
  },
  PTT: {
    code: 'PTT',
    name: 'Partial Thromboplastin Time',
    nameAr: 'زمن الثرومبوبلاستين الجزئي',
    category: 'coagulation',
    unit: 'seconds',
    referenceRangeLow: 25,
    referenceRangeHigh: 35,
    isCritical: false,
    criticalLow: null,
    criticalHigh: null,
  },
};
