import { ICUAdmission } from '../../domain/entities/ICUAdmission';

export interface ICUAdmissionRecord {
  id?: string;
  patientId: string;
  fullName: string;
  fullNameAr: string;
  age: number;
  gender: 'male' | 'female';
  weightKg: number;
  heightCm: number;
  bmi: number;
  mrn: string;
  admissionDate: string;
  admissionSource: string;
  icuType: string;
  primaryDiagnosis: string;
  primaryDiagnosisAr: string;
  secondaryDiagnoses?: string;
  secondaryDiagnosesAr?: string;
  apacheIIScore?: number;
  gcs?: number;
  severityLevel: string;
  heartRate?: number;
  bpSystolic?: number;
  bpDiastolic?: number;
  respiratoryRate?: number;
  temperature?: number;
  o2Sat?: number;
  oxygenTherapy: string;
  ventilatorType?: string;
  preAdmissionWeightKg?: number;
  weightChangeKg?: number;
  weightChangePercent?: number;
  appetiteBeforeAdmission: string;
  eatingDifficulty: string;
  npoStatus: boolean;
  npoDuration?: string;
  previousNutritionSupport: string;
  hasDiabetes: boolean;
  diabetesType?: string;
  hasCardiovascular: boolean;
  hasKidney: boolean;
  kidneyStage?: string;
  hasLiver: boolean;
  hasLung: boolean;
  hasGI: boolean;
  hasCancer: boolean;
  cancerStage?: string;
  allergies?: string;
  allergiesAr?: string;
  previousSurgeries?: string;
  previousSurgeriesAr?: string;
  medications?: string;
  medicationsAr?: string;
  hemoglobin?: number;
  wbc?: number;
  platelets?: number;
  creatinine?: number;
  bun?: number;
  eGFR?: number;
  sodium?: number;
  potassium?: number;
  chloride?: number;
  glucose?: number;
  hba1c?: number;
  totalProtein?: number;
  albumin?: number;
  totalBilirubin?: number;
  alt?: number;
  ast?: number;
  triglycerides?: number;
  cholesterol?: number;
  stampScore?: number;
  malnutritionRisk?: string;
  nutritionConcern: boolean;
  admissionReason: string;
  admissionReasonAr: string;
  specialConcerns?: string;
  specialConcernsAr?: string;
  physicianNotes?: string;
  physicianNotesAr?: string;
  dietitianNotes?: string;
  dietitianNotesAr?: string;
  nutritionConsent: boolean;
  guardianConsent?: boolean;
  signedBy?: string;
  consentDate?: string;
  createdBy: string;
  createdAt?: string;
  updatedAt?: string;
  isTransferredToICU: boolean;
  transferredAt?: string;
}

export interface IICUAdmissionRepository {
  create(record: ICUAdmissionRecord): Promise<string>;
  getByPatientId(patientId: string): Promise<ICUAdmissionRecord[]>;
  getById(id: string): Promise<ICUAdmissionRecord | null>;
}
