export type IcuType = 'medical' | 'surgical' | 'cardiac' | 'neuro' | 'pediatric' | 'neonatal';
export type SeverityLevel = 'mild' | 'moderate' | 'severe' | 'critical';
export type AdmissionSource = 'er' | 'ward' | 'transfer' | 'other';
export type OxygenTherapy = 'none' | 'nasal_cannula' | 'mask' | 'ventimeter' | 'mechanical';
export type AppetiteLevel = 'normal' | 'decreased' | 'poor' | 'none';
export type EatingDifficulty = 'none' | 'dysphagia' | 'chewing' | 'swallowing';
export type PreviousNutritionSupport = 'none' | 'oral_supplements' | 'enteral' | 'parenteral';
export type MalnutritionRisk = 'low' | 'medium' | 'high';

export interface ICUAdmission {
  id: string;
  patientId: string;
  fullName: string;
  fullNameAr: string;
  age: number;
  gender: 'male' | 'female';
  weightKg: number;
  heightCm: number;
  bmi: number;
  mrn: string;
  admissionDate: string;
  admissionSource: AdmissionSource;
  icuType: IcuType;
  primaryDiagnosis: string;
  primaryDiagnosisAr: string;
  secondaryDiagnoses: string | null;
  secondaryDiagnosesAr: string | null;
  apacheIIScore: number | null;
  gcs: number | null;
  severityLevel: SeverityLevel;
  heartRate: number | null;
  bpSystolic: number | null;
  bpDiastolic: number | null;
  respiratoryRate: number | null;
  temperature: number | null;
  o2Sat: number | null;
  oxygenTherapy: OxygenTherapy;
  ventilatorType: string | null;
  preAdmissionWeightKg: number | null;
  weightChangeKg: number | null;
  weightChangePercent: number | null;
  appetiteBeforeAdmission: AppetiteLevel;
  eatingDifficulty: EatingDifficulty;
  npoStatus: boolean;
  npoDuration: string | null;
  previousNutritionSupport: PreviousNutritionSupport;
  hasDiabetes: boolean;
  diabetesType: string | null;
  hasCardiovascular: boolean;
  hasKidney: boolean;
  kidneyStage: string | null;
  hasLiver: boolean;
  hasLung: boolean;
  hasGI: boolean;
  hasCancer: boolean;
  cancerStage: string | null;
  allergies: string | null;
  allergiesAr: string | null;
  previousSurgeries: string | null;
  previousSurgeriesAr: string | null;
  medications: string | null;
  medicationsAr: string | null;
  hemoglobin: number | null;
  wbc: number | null;
  platelets: number | null;
  creatinine: number | null;
  bun: number | null;
  eGFR: number | null;
  sodium: number | null;
  potassium: number | null;
  chloride: number | null;
  glucose: number | null;
  hba1c: number | null;
  totalProtein: number | null;
  albumin: number | null;
  totalBilirubin: number | null;
  alt: number | null;
  ast: number | null;
  triglycerides: number | null;
  cholesterol: number | null;
  stampScore: number | null;
  malnutritionRisk: MalnutritionRisk | null;
  nutritionConcern: boolean;
  admissionReason: string;
  admissionReasonAr: string;
  specialConcerns: string | null;
  specialConcernsAr: string | null;
  physicianNotes: string | null;
  physicianNotesAr: string | null;
  dietitianNotes: string | null;
  dietitianNotesAr: string | null;
  nutritionConsent: boolean;
  guardianConsent: boolean | null;
  signedBy: string | null;
  consentDate: string | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  isTransferredToICU: boolean;
  transferredAt: string | null;
}
